In this notebook, I'm testing to see if the BIDS events are erased once they are used to select epochs with specific labels, or if they are retained in the metadata of those epochs.

In [8]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import sys
import os

print(sys.path)
sys.path.append("C:/Users/jz421/Desktop/GlobalLocal/IEEG_Pipelines/") #need to do this cuz otherwise ieeg isn't added to path...

# Get the absolute path to the directory containing the current script
# For GlobalLocal/src/analysis/preproc/make_epoched_data.py, this is GlobalLocal/src/analysis/preproc
try:
    # This will work if running as a .py script
    current_file_path = os.path.abspath(__file__)
    current_script_dir = os.path.dirname(current_file_path)
except NameError:
    # This will be executed if __file__ is not defined (e.g., in a Jupyter Notebook)
    # os.getcwd() often gives the directory of the notebook,
    # or the directory from which the Jupyter server was started.
    current_script_dir = os.getcwd()

# Navigate up three levels to get to the 'GlobalLocal' directory
project_root = os.path.abspath(os.path.join(current_script_dir, '..', '..', '..'))

# Add the 'GlobalLocal' directory to sys.path if it's not already there
if project_root not in sys.path:
    sys.path.insert(0, project_root) # insert at the beginning to prioritize it

import mne
from src.analysis.config import experiment_conditions
import src.analysis.utils.general_utils as utils # import utils functions one by one by name
from src.analysis.utils.epoch_metadata_utils import parse_event_name, make_metadata_from_event_names, add_previous_trial_info
import pandas as pd

['/hpc/group/coganlab/jz421/GlobalLocal', '/hpc/home/jz421/miniconda3/envs/ieeg/lib/python311.zip', '/hpc/home/jz421/miniconda3/envs/ieeg/lib/python3.11', '/hpc/home/jz421/miniconda3/envs/ieeg/lib/python3.11/lib-dynload', '', '/hpc/home/jz421/miniconda3/envs/ieeg/lib/python3.11/site-packages', 'C:/Users/jz421/Desktop/GlobalLocal/IEEG_Pipelines/']

In [2]:
HOME = os.path.expanduser("~")
USER = os.path.basename(HOME)
    
if os.name == 'nt':  # Windows
    LAB_root = os.path.join(HOME, "Box", "CoganLab")
elif sys.platform == 'darwin':  # macOS
    LAB_root = os.path.join(HOME, "Library", "CloudStorage", "Box-Box", "CoganLab")
else:  # Linux (cluster)
    # Check if we're on the cluster by looking for /cwork directory
    if os.path.exists(f"/cwork/{USER}"):
        LAB_root = f"/cwork/{USER}"
    else:
        # Fallback for other Linux systems
        LAB_root = os.path.join(HOME, "CoganLab")

In [9]:
subjects = ['D0057']
task='GlobalLocal'
conditions = experiment_conditions.stimulus_all_conditions # set this to whichever conditions you're running
epochs_root_file = "Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_thresh_perc_5.0_70.0-150.0_Hz_padLength_0.5s_stat_func_ttest_ind_equal_var_False_nan_policy_omit"
condition_names = [condition for condition in conditions.keys()]

In [10]:
subjects_mne_objects = utils.create_subjects_mne_objects_dict(subjects=subjects, epochs_root_file=epochs_root_file, conditions=conditions, task="GlobalLocal", just_HG_ev1_rescaled=True, acc_trials_only=False)

Loading data for subject: D0057
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0057/D0057_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_thresh_perc_5.0_70.0-150.0_Hz_padLength_0.5s_stat_func_ttest_ind_equal_var_False_nan_policy_omit_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
449 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0057/D0057_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_thresh_perc_5.0_70.0-150.0_Hz_padLength_0.5s_stat_func_ttest_ind_equal_var_False_nan_policy_omit_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
449 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
  Loading condition: Stimulus

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:428: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 29 columns
449 matching events found
No baseline correction applied
    Stimulus: 449 valid trials out of 449
  Loading condition: Stimulus

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:428: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 29 columns
449 matching events found
No baseline correction applied
    Stimulus: 449 valid trials out of 449

In [11]:
test_epochs = subjects_mne_objects['D0057']['Stimulus']['HG_ev1_rescaled']

In [12]:
test_epochs.metadata

,full_event_name,event,congruency,incongruent_proportion,task_sequence,switch_proportion,big_letter,small_letter,task,target_letter,...,reaction_time,prev_congruency,prev_incongruent_proportion,prev_task_sequence,prev_switch_proportion,prev_accuracy,prev_reaction_time,prev_big_letter,prev_small_letter,prev_task
1,Stimulus/i25.0/n75.0/BigLetters/SmallLetterh/T...,Stimulus,i,25.0,n,75.0,s,h,g,s,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Stimulus/c25.0/s75.0/BigLetters/SmallLetters/T...,Stimulus,c,25.0,s,75.0,s,s,l,s,...,1616.0,i,25.0,n,75.0,0.0,NaN,s,h,g
4,Stimulus/c25.0/s75.0/BigLetters/SmallLetters/T...,Stimulus,c,25.0,s,75.0,s,s,g,s,...,2000.0,c,25.0,s,75.0,0.0,1616.0,s,s,l
6,Stimulus/c25.0/r75.0/BigLetterh/SmallLetterh/T...,Stimulus,c,25.0,r,75.0,h,h,g,h,...,1916.0,c,25.0,s,75.0,1.0,2000.0,s,s,g
8,Stimulus/i25.0/s75.0/BigLetters/SmallLetterh/T...,Stimulus,i,25.0,s,75.0,s,h,l,h,...,1300.0,c,25.0,r,75.0,1.0,1916.0,h,h,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890,Stimulus/i75.0/s75.0/BigLetterh/SmallLetters/T...,Stimulus,i,75.0,s,75.0,h,s,l,s,...,1066.0,i,75.0,s,75.0,1.0,1466.0,h,s,g
892,Stimulus/i75.0/s75.0/BigLetters/SmallLetterh/T...,Stimulus,i,75.0,s,75.0,s,h,g,s,...,1433.0,i,75.0,s,75.0,1.0,1066.0,h,s,l
894,Stimulus/i75.0/s75.0/BigLetters/SmallLetterh/T...,Stimulus,i,75.0,s,75.0,s,h,l,h,...,899.0,i,75.0,s,75.0,1.0,1433.0,s,h,g
896,Stimulus/i75.0/s75.0/BigLetters/SmallLetterh/T...,Stimulus,i,75.0,s,75.0,s,h,g,s,...,1400.0,i,75.0,s,75.0,1.0,899.0,s,h,l
898,Stimulus/i75.0/r75.0/BigLetters/SmallLetterh/T...,Stimulus,i,75.0,r,75.0,s,h,g,s,...,483.0,i,75.0,s,75.0,1.0,1400.0,s,h,g

playing around with metadata code

In [6]:
event_name = 'Stimulus/i25.0/r25.0/BigLetters/SmallLetterh/Taskg/TargetLetters/Responded1.0/ParticipantResponse115.0/CorrectResponse115.0/TrialCount261.0/BlockTrialCount37.0/ReactionTime1350.0/Accuracy1.0/D57'

In [9]:
test_epochs.metadata = make_metadata_from_event_names(test_epochs)
test_epochs.metadata = add_previous_trial_info(test_epochs.metadata)
prev_switch = test_epochs['prev_task_sequence == "s"']

test_epochs.metadata

Adding metadata with 20 columns
Replacing existing metadata with 29 columns

,full_event_name,event,congruency,incongruent_proportion,task_sequence,switch_proportion,big_letter,small_letter,task,target_letter,...,reaction_time,prev_congruency,prev_incongruent_proportion,prev_task_sequence,prev_switch_proportion,prev_accuracy,prev_reaction_time,prev_big_letter,prev_small_letter,prev_task
1,Stimulus/i25.0/n75.0/BigLetters/SmallLetterh/T...,Stimulus,i,25.0,n,75.0,s,h,g,s,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Stimulus/c25.0/s75.0/BigLetters/SmallLetters/T...,Stimulus,c,25.0,s,75.0,s,s,l,s,...,1616.0,i,25.0,n,75.0,0.0,NaN,s,h,g
4,Stimulus/c25.0/s75.0/BigLetters/SmallLetters/T...,Stimulus,c,25.0,s,75.0,s,s,g,s,...,2000.0,c,25.0,s,75.0,0.0,1616.0,s,s,l
6,Stimulus/c25.0/r75.0/BigLetterh/SmallLetterh/T...,Stimulus,c,25.0,r,75.0,h,h,g,h,...,1916.0,c,25.0,s,75.0,1.0,2000.0,s,s,g
8,Stimulus/i25.0/s75.0/BigLetters/SmallLetterh/T...,Stimulus,i,25.0,s,75.0,s,h,l,h,...,1300.0,c,25.0,r,75.0,1.0,1916.0,h,h,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890,Stimulus/i75.0/s75.0/BigLetterh/SmallLetters/T...,Stimulus,i,75.0,s,75.0,h,s,l,s,...,1066.0,i,75.0,s,75.0,1.0,1466.0,h,s,g
892,Stimulus/i75.0/s75.0/BigLetters/SmallLetterh/T...,Stimulus,i,75.0,s,75.0,s,h,g,s,...,1433.0,i,75.0,s,75.0,1.0,1066.0,h,s,l
894,Stimulus/i75.0/s75.0/BigLetters/SmallLetterh/T...,Stimulus,i,75.0,s,75.0,s,h,l,h,...,899.0,i,75.0,s,75.0,1.0,1433.0,s,h,g
896,Stimulus/i75.0/s75.0/BigLetters/SmallLetterh/T...,Stimulus,i,75.0,s,75.0,s,h,g,s,...,1400.0,i,75.0,s,75.0,1.0,899.0,s,h,l
898,Stimulus/i75.0/r75.0/BigLetters/SmallLetterh/T...,Stimulus,i,75.0,r,75.0,s,h,g,s,...,483.0,i,75.0,s,75.0,1.0,1400.0,s,h,g

In [13]:

# Assuming you have your epochs object loaded
df = make_metadata_from_event_names(test_epochs)
print(df.shape)          # Should be (n_epochs, n_columns)
print(df.columns.tolist()) # Check all column names look right

(449, 20)
['full_event_name', 'event', 'congruency', 'incongruent_proportion', 'task_sequence', 'switch_proportion', 'big_letter', 'small_letter', 'task', 'target_letter', 'responded', 'ParticipantResponsenan', 'correct_response', 'trial_count', 'block_trial_count', 'ReactionTimenan', 'accuracy', 'subject', 'participant_response', 'reaction_time']

In [14]:
df.head()

,full_event_name,event,congruency,incongruent_proportion,task_sequence,switch_proportion,big_letter,small_letter,task,target_letter,responded,ParticipantResponsenan,correct_response,trial_count,block_trial_count,ReactionTimenan,accuracy,subject,participant_response,reaction_time
0,Stimulus/i25.0/n75.0/BigLetters/SmallLetterh/T...,Stimulus,i,25.0,n,75.0,s,h,g,s,0.0,True,115.0,1.0,1.0,True,0.0,D57,NaN,NaN
1,Stimulus/c25.0/s75.0/BigLetters/SmallLetters/T...,Stimulus,c,25.0,s,75.0,s,s,l,s,1.0,NaN,115.0,2.0,2.0,NaN,0.0,D57,114.0,1616.0
2,Stimulus/c25.0/s75.0/BigLetters/SmallLetters/T...,Stimulus,c,25.0,s,75.0,s,s,g,s,1.0,NaN,115.0,3.0,3.0,NaN,1.0,D57,115.0,2000.0
3,Stimulus/c25.0/r75.0/BigLetterh/SmallLetterh/T...,Stimulus,c,25.0,r,75.0,h,h,g,h,1.0,NaN,114.0,4.0,4.0,NaN,1.0,D57,114.0,1916.0
4,Stimulus/i25.0/s75.0/BigLetters/SmallLetterh/T...,Stimulus,i,25.0,s,75.0,s,h,l,h,1.0,NaN,114.0,5.0,5.0,NaN,1.0,D57,114.0,1300.0