In [1]:

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import sys
import os

# Get the absolute path to the directory containing the current script
try:
    current_file_path = os.path.abspath(__file__)
    current_script_dir = os.path.dirname(current_file_path)
except NameError:
    current_script_dir = os.getcwd()

# Navigate up two levels to get to the 'GlobalLocal' directory
project_root = os.path.abspath(os.path.join(current_script_dir, '..', '..'))

if project_root not in sys.path:
    sys.path.insert(0, project_root)

from ieeg.io import get_data
import mne
import numpy as np
import json

import matplotlib.pyplot as plt

from src.analysis.config import experiment_conditions
from src.analysis.config.plotting_parameters import plotting_parameters as plot_params
from src.analysis.config.condition_registry import (
    get_comparisons,
    get_conditions_obj,
    get_subtraction_pairs,
    get_anova_factors,
    get_anova_interactions,
)
import src.analysis.utils.general_utils as utils
from src.analysis.power.power_traces import (
    make_multi_channel_evokeds_for_all_conditions_and_rois,
    plot_power_traces_for_all_rois,
    create_subtracted_evokeds_dict,
    time_perm_cluster_between_two_evokeds,
    process_windowed_data_for_anova,
    run_windowed_anova_cluster_correction,
    anova_results_to_interaction_results_for_plotting,
    plot_anova_interaction_results,
    run_within_electrode_windowed_anova_cluster_correction,
    load_significant_electrodes, 
    create_windowed_anova_dataframe
)

from src.analysis.vis.power_traces_anova_f_traces_vis import (
    plot_per_electrode_power_traces,
    plot_per_electrode_F_traces,
)

from types import SimpleNamespace as ns

Qt5Agg backend not available, using default backend
Qt5Agg backend not available, using default backend

In [6]:
# ------------------------------------------------------------------
# 1. Resolve LAB_root
# ------------------------------------------------------------------
args = ns(
    LAB_root = None,
    condition_label = 'stimulus_lwpc_conditions',
    subjects = ['D0057', 'D0059', 'D0063', 'D0065', 'D0069', 'D0077', 'D0090', 'D0094', 'D0100', 'D0102', 'D0103', 'D0107A', 'D0110', 'D0116', 'D0117', 'D0121', 'D0133', 'D0134', 'D0137', 'D0138', 'D0139A', 'D0144', 'D0145', 'D0146'],
    electrodes = 'sig',
    task = 'GlobalLocal',
    epochs_root_file = "Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20",
    anova_unit='roi',
    save_dir = "/hpc/home/jz421/coganlab/jz421/GlobalLocal/dcc_scripts/power/figs/sandbox",
    rois_dict = {
        'lpfc': ["G_front_inf-Opercular", "G_front_inf-Orbital", "G_front_inf-Triangul", "G_front_middle", "G_front_sup", "Lat_Fis-ant-Horizont", "Lat_Fis-ant-Vertical", "S_circular_insula_ant", "S_circular_insula_sup", "S_front_inf", "S_front_middle", "S_front_sup"]
    },
    acc_trials_only = True,
    anova_labels_csv = "/hpc/home/jz421/coganlab/jz421/GlobalLocal/dcc_scripts/stats/results/Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_ind_equal_var_False_nan_policy_omit/anova_conjunction_window_0.0to1.5s_sig_lpfc_condition_none/anova_labels.csv",
    anova_label_effect = 'lwpc',
    anova_label_correction = 'flags',
    anova_label_alpha = 0.05,
    anova_label_roi = None,
    statistical_method = 'anova',
    window_size = 64,
    step_size = 16,
    split_clusters_by_sign = True,
    min_trials_per_cell = 4,
    sampling_rate = 256,
    
    p_thresh_for_time_perm_cluster_stats = 0.05,
    p_cluster = 0.05,
    permutation_type = 'independent',
    n_perm = 500,
    tails=2,
    
    n_jobs=-1
)


if args.LAB_root is None:
    HOME = os.path.expanduser("~")
    USER = os.path.basename(HOME)

    if os.name == 'nt':  # Windows
        LAB_root = os.path.join(HOME, "Box", "CoganLab")
    elif sys.platform == 'darwin':  # macOS
        LAB_root = os.path.join(HOME, "Library", "CloudStorage",
                                "Box-Box", "CoganLab")
    else:  # Linux (cluster)
        if os.path.exists(f"/cwork/{USER}"):
            LAB_root = f"/cwork/{USER}"
        else:
            LAB_root = os.path.join(HOME, "CoganLab")
else:
    LAB_root = args.LAB_root

In [7]:
# ------------------------------------------------------------------
# 2. Resolve conditions / comparisons / subtraction_pairs / anova
#    config from the registry, driven by condition_label.
# ------------------------------------------------------------------
condition_label = args.condition_label
conditions = get_conditions_obj(condition_label)
condition_names = list(conditions.keys())
condition_comparisons = get_comparisons(condition_label)
subtraction_pairs = get_subtraction_pairs(condition_label)
anova_factors = get_anova_factors(condition_label)
anova_interactions = get_anova_interactions(condition_label)

conditions_save_name = utils.get_conditions_save_name(
    conditions, experiment_conditions, len(args.subjects)
)

In [8]:
# ------------------------------------------------------------------
# 3. Build save dir, electrodes, mne objects
# ------------------------------------------------------------------
config_dir = os.path.join(project_root, 'src', 'analysis', 'config')
subjects_electrodestoROIs_dict = utils.make_or_load_subjects_electrodes_to_ROIs_dict(
    subjects=args.subjects, save_dir=config_dir,
    filename='subjects_electrodestoROIs_dict.json'
)

layout = get_data(args.task, root=LAB_root)

if args.save_dir:
    save_dir = args.save_dir
else:
    save_dir = os.path.join(layout.root, 'derivatives', 'freqFilt', 'figs',
                            f"{args.epochs_root_file}", f"anova_{args.anova_unit}")
    
os.makedirs(save_dir, exist_ok=True)
print(f"Save directory created or already exists at: {save_dir}")

sig_chans_per_subject = utils.get_sig_chans_per_subject(
    args.subjects, args.epochs_root_file, task=args.task, LAB_root=LAB_root
)

rois = list(args.rois_dict.keys())
all_electrodes_per_subject_roi, sig_electrodes_per_subject_roi = \
    utils.make_sig_electrodes_per_subject_and_roi_dict(
        args.rois_dict, subjects_electrodestoROIs_dict, sig_chans_per_subject
    )

subjects_mne_objects = utils.create_subjects_mne_objects_dict(
    subjects=args.subjects, epochs_root_file=args.epochs_root_file,
    conditions=conditions, task=args.task,
    just_HG_ev1_rescaled=True, acc_trials_only=args.acc_trials_only
)

if args.electrodes == 'all':
    raw_electrodes = all_electrodes_per_subject_roi
    elec_string_to_add_to_filename = 'all_elecs'
elif args.electrodes == 'sig':
    raw_electrodes = sig_electrodes_per_subject_roi
    elec_string_to_add_to_filename = 'sig_elecs'
else:
    raise ValueError("electrodes input must be set to all or sig")

electrodes = utils.filter_electrode_lists_against_subjects_mne_objects(
    rois, raw_electrodes, subjects_mne_objects
)

dropped_electrodes, _ = utils.find_difference_between_two_electrode_lists(
    raw_electrodes, electrodes
)
print("\n--- Summary of Dropped Electrodes ---")
total_dropped = 0
for roi, sub_dict in dropped_electrodes.items():
    if not sub_dict:
        continue
    print(f"ROI: {roi}")
    for sub, elec_list in sub_dict.items():
        if elec_list:
            print(f"  - Subject {sub}: Dropped {len(elec_list)} electrode(s)")
            total_dropped += len(elec_list)
print(f"Total electrodes dropped across all subjects/ROIs: {total_dropped}")
print("-------------------------------------\n")

Attempting to load the subjects' electrodes-to-ROIs dictionary...
Loaded data from /hpc/group/coganlab/jz421/GlobalLocal/src/analysis/config/subjects_electrodestoROIs_dict.json
Dictionary loaded successfully. Ready to proceed!
Save directory created or already exists at: /hpc/home/jz421/coganlab/jz421/GlobalLocal/dcc_scripts/power/figs/sandbox
Loaded significant channels for subject D0057
Loaded significant channels for subject D0059
Loaded significant channels for subject D0063
Loaded significant channels for subject D0065
Loaded significant channels for subject D0069
Loaded significant channels for subject D0077
Loaded significant channels for subject D0090
Loaded significant channels for subject D0094
Loaded significant channels for subject D0100
Loaded significant channels for subject D0102
Loaded significant channels for subject D0103
Loaded significant channels for subject D0107A
Loaded significant channels for subject D0110
Loaded significant channels for subject D0116
Loaded significant channels for subject D0117
Loaded significant channels for subject D0121
Loaded significant channels for subject D0133
Loaded significant channels for subject D0134
Loaded significant channels for subject D0137
Loaded significant channels for subject D0138
Loaded significant channels for subject D0139A
Loaded significant channels for subject D0144
Loaded significant channels for subject D0145
Loaded significant channels for subject D0146
For subject D0057, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['RAI6', 'RAI12', 'RAI13', 'RAI14', 'RAI15', 'RAI16', 'RPI15', 'RPI14', 'RAMF10', 'RAMF11', 'RAMF12', 'RAMF13', 'RAMF14', 'RAIF11', 'RAIF12', 'RAIF13', 'RAIF14']
For subject D0059, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LMMF9', 'LMMF11', 'LMMF10', 'LMMF12', 'LPSF16']
For subject D0063, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LASF10', 'LASF11', 'LASF14', 'LASF15', 'LASF16', 'LMSF5', 'LMSF6', 'LMSF12', 'LPSF10', 'LPSF12', 'ROF16', 'RAI16', 'RAMF11', 'RAMF12', 'RAMF13', 'RAMF14', 'RMMF13', 'RMMF14', 'RAI4', 'RAI6', 'RAI5', 'RAI10', 'RAI11', 'RASF15', 'RASF16', 'RMSF8', 'RMSF9', 'RMSF10', 'RMSF11', 'RMSF12', 'RMSF7', 'RAMF8', 'RAMF9', 'RAMF10', 'RMMF9', 'RMMF10']
For subject D0065, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['RASF13', 'RASF14', 'RASF15', 'RASF16', 'RMSF11', 'RMSF12', 'RMSF13', 'RMSF14', 'RI7']
For subject D0069, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LOF8']
For subject D0071, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['RFO14', 'RFO16', 'RIA4', 'RIP6', 'RIA5', 'RIA11', 'RIA12', 'RIA13', 'RIA14', 'RIA16', 'RIP14', 'RIP15', 'RIP16']
For subject D0077, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: []
For subject D0090, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['RFO15', 'RIA6', 'RIA11', 'RIA12', 'RIA14', 'RIA15', 'RIA16', 'RIP7']
For subject D0094, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LFO12', 'LFO13', 'LFO15', 'LFO16', 'LFAM8', 'LFAM9', 'LFAM10', 'LFAM13', 'LFAM14', 'LFPM10', 'LFPM11', 'LFPM12', 'LPAS1', 'LIA16', 'LFAI3', 'LFAI4', 'LFAI5', 'LFPI10', 'LPAI9', 'LPAI10', 'LIA4', 'LIA5', 'LFAI9', 'LFAI10', 'LIA11', 'LIA12', 'LIA13', 'LIA14']
For subject D0100, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: []
For subject D0102, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['RFO13', 'RFO14', 'RFAM15', 'RFAI2', 'RFAI3']
For subject D0103, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LFAM8', 'LFAM9', 'LAI13', 'LAI14', 'LFAM15', 'LAI4', 'LAI7', 'LAI8', 'LAI18', 'LFO15', 'LFAI4']
For subject D0107A, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['RFOA16', 'RFOA17', 'RFOA18', 'RFAI3', 'RIA5', 'RIA6', 'RFAM7', 'RFAM9', 'RFAM10', 'RFAM11', 'RFAM12', 'RFMM9', 'RFMM11', 'RFMM12', 'RFMM13', 'RFMM14', 'RFMM15', 'RFMM8', 'RIA12', 'RIA13', 'RIA14', 'RIA15', 'RIA16', 'RIA17', 'RIA18']
For subject D0110, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LASF10', 'LOF13', 'LOF15', 'LINS4', 'LINS5']
For subject D0116, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LFOA14', 'LFOA17', 'LFOA18', 'LFOP15', 'LFAM10', 'LFAM11', 'LFMM14', 'LAI12', 'LAI16', 'LFAM12', 'LAI7', 'LAI8', 'LFMI3', 'LFMI5', 'LFMI6', 'RFOA14', 'RFOA15', 'RFOA16', 'RFOP15', 'RFMM10', 'RFMM11', 'RFMM12', 'RAI7', 'RAI11', 'RAI12', 'RAI14', 'RAI15', 'RAI16', 'RAI17', 'RFMI4']
For subject D0117, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['RMOF15', 'RINSA15', 'RINSA16', 'RLOF10', 'RLOF11', 'RLOF16', 'RINSA3', 'RINSA11', 'RINSA12', 'RINSA13', 'RINSA14']
For subject D0121, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LFOA15', 'LFOP12', 'LFO5', 'LFO6', 'LFO8', 'LFO9', 'LFO12', 'LFO13', 'LFO14', 'LFO15', 'LFO16', 'LFO17', 'LFO18', 'LFA1', 'LFA2', 'LFP16', 'LFP17', 'LFPS1', 'LFPS2', 'LFPP1', 'LFOP13', 'LFOP15', 'LFOP16', 'LFOP18', 'LFA7', 'LFA8', 'LFAS6', 'LFAM8', 'LFAM9', 'LFA9', 'LFA10', 'LFA11', 'LFA12', 'LFAM10', 'LFAM11', 'LFAM12', 'LFMM8', 'LFMM9', 'LFMM10', 'LFMM11', 'LFMM12', 'LFAS7', 'LFAS8', 'LFAS9', 'LFAS10', 'LFMS7', 'LFMS9', 'LFMS10', 'LFMS11', 'LFMS12', 'LFPS6', 'LFPS7', 'LFPS9', 'LFPS10', 'LFPP7', 'LFPP9', 'LFPP10', 'LFMI4', 'LFMI5', 'LFMI8', 'LFMI9']
For subject D0130, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: []
For subject D0133, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LFAA7', 'LFAA9', 'LFAA10', 'LFAA11', 'LFAI5', 'LFAI6', 'LFAI7', 'LFAI8', 'LFAI9', 'LFAI10', 'LFAM8', 'LFAP6', 'LFAP7', 'LFAP8', 'LFAP9', 'LFAP10', 'LFAI3', 'LFAI4', 'LFAM5', 'LFAM6', 'LFAM7', 'LFMM8', 'LFMM9', 'LFMM10', 'LFAP3', 'LFPA2', 'RFAL8', 'RFAL9', 'RFAL10', 'RFAL11', 'RFAL12', 'RFAM4', 'RFAM6', 'RFAM7', 'RFAM8', 'RFAM9', 'RFAM10', 'RFAM11', 'RFAM12']
For subject D0134, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LFAS7', 'LFAS8', 'LLeSS9', 'LFAM4', 'LLeSS8', 'LFAM5', 'LFAM9', 'LFAM10', 'LLeSS10', 'LLeSS11', 'LLeSM10', 'LINS9', 'LINS12', 'LINS13', 'LINS14', 'LINS15', 'LLeSL8', 'LLeSL9', 'LLeSL10', 'LINS5', 'LFMEG1', 'LFMEG2', 'RFAS5', 'RFAS6', 'RFAS7', 'RFAS8', 'RFAM14', 'RINS10', 'RSFMEG1', 'RINS6', 'RINS7', 'RIFMEG1', 'RIFMEG2', 'RIFMEG7', 'RIFMEG8', 'RIFMEG9', 'RIFMEG10', 'RINS11', 'RINS12', 'RINS13']
For subject D0137, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LAI6', 'LAI7', 'LAI10', 'LAI15', 'LAI17', 'LAI18']
For subject D0138, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LFAM14', 'LFAM15', 'LFAM16', 'LFAM17', 'LFAM18', 'LFOA16', 'LFOA18', 'LFOP16', 'LFOP17', 'LFOP18', 'LFOA14', 'LFOA15', 'LAI2', 'LAI3', 'LAI4', 'LAI5', 'LAI13', 'LAI14', 'LAI15', 'LAI16']
For subject D0139A, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LFOP13', 'LFOP14', 'LFOP16', 'LFOP17', 'LFOP18', 'LFAI2', 'LIA6', 'LFAI3', 'LFAI4', 'LIA13', 'LIA14', 'LIA15', 'LIA16', 'LIA17']
For subject D0144, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LOF13', 'LOF14', 'LAI10', 'LAI11', 'LOF16', 'LFAI11', 'LFAI12', 'LFAI13', 'LFAI14', 'LFMM8', 'LFMM9', 'LFMM10', 'LFMM12', 'LAI13', 'LAI14', 'LAI6', 'LAI7']
For subject D0145, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['RFO10', 'RFO11', 'RFO12', 'RIA10', 'RIA11', 'RIA14', 'LFO10']
For subject D0146, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LFAM8', 'LFAM9', 'LFAM10', 'LFAM11', 'LFOA12', 'LFAM13', 'LFAM14', 'LFOA13', 'LFOA14', 'LFOA15', 'LFOA16', 'LFOP16', 'LFOP15', 'LFMI2', 'LFMI3', 'LFMI4', 'LFMI7', 'LFMI8', 'LAI10', 'LAI11', 'LAI13', 'LAI14', 'LAI15']
Subject D0057 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['RAI6', 'RPI15', 'RPI14', 'RAMF12', 'RAMF13', 'RAMF14']
Subject D0059 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LMMF9', 'LMMF11', 'LMMF10', 'LMMF12', 'LPSF16']
Subject D0063 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LASF10', 'LMSF5', 'LPSF12', 'RAMF11', 'RAMF12', 'RMMF13', 'RMMF14', 'RAI4', 'RAI6', 'RMMF10']
Subject D0065 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: []
Subject D0069 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: []
Subject D0071 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: []
Subject D0077 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: []
Subject D0090 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['RIA6', 'RIA11']
Subject D0094 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LFAM8', 'LFAM9', 'LFAM10', 'LFPM10', 'LFPM11', 'LFPM12', 'LFPI10', 'LPAI9', 'LFAI9', 'LFAI10', 'LIA11', 'LIA12']
Subject D0100 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: []
Subject D0102 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['RFO13', 'RFO14', 'RFAM15']
Subject D0103 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LFAM8', 'LFAM9', 'LAI13', 'LAI14', 'LAI4', 'LAI7', 'LAI8', 'LFO15', 'LFAI4']
Subject D0107A significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['RFAI3', 'RIA6', 'RFAM7', 'RFAM9', 'RFAM10', 'RFAM12', 'RFMM8']
Subject D0110 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LASF10', 'LINS4']
Subject D0116 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LFAM10', 'LFAM11', 'LAI12', 'LAI16', 'LFAM12', 'LAI7', 'LAI8', 'LFMI3', 'RFOA14', 'RFOA16', 'RFMM10', 'RFMM11', 'RFMM12', 'RAI11', 'RAI12', 'RAI15', 'RAI17']
Subject D0117 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['RLOF10', 'RLOF11', 'RINSA3']
Subject D0121 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LFPS1', 'LFPS2', 'LFPP1', 'LFA9', 'LFA10', 'LFA11', 'LFA12', 'LFAM10', 'LFMM8', 'LFMM9', 'LFMM10', 'LFMM11', 'LFMM12', 'LFAS7', 'LFPS6', 'LFMI4', 'LFMI5']
Subject D0130 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: []
Subject D0133 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LFAA7', 'LFAI5', 'LFAI6', 'LFAI7', 'LFAI8', 'LFAI9', 'LFAI10', 'LFAP6', 'LFAP8', 'LFAI3', 'LFAI4', 'LFAM5', 'LFAM6', 'LFMM8', 'LFMM9', 'LFMM10', 'RFAL8', 'RFAL11', 'RFAM4', 'RFAM6']
Subject D0134 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LLeSS9', 'LLeSS8', 'LFAM9', 'LLeSS10', 'LLeSS11', 'LINS9', 'LINS12', 'LINS13', 'LINS14', 'LINS15', 'LFMEG1', 'RINS10', 'RINS6', 'RINS7', 'RIFMEG1', 'RIFMEG2', 'RIFMEG7', 'RINS11', 'RINS12', 'RINS13']
Subject D0137 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LAI7', 'LAI10', 'LAI15', 'LAI17', 'LAI18']
Subject D0138 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LFOP17', 'LAI3', 'LAI4', 'LAI5']
Subject D0139A significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LFOP13', 'LFOP14', 'LFAI2', 'LFAI3', 'LIA13', 'LIA14', 'LIA15', 'LIA16', 'LIA17']

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 143 valid trials out of 143
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
55 matching events found
No baseline correction applied
    Stimulus_c75: 55 valid trials out of 55

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

  Loading condition: Stimulus_i25
Adding metadata with 30 columns
43 matching events found
No baseline correction applied
    Stimulus_i25: 43 valid trials out of 43

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

  Loading condition: Stimulus_i75
Adding metadata with 30 columns
164 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 164 valid trials out of 164
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
143 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 143 valid trials out of 143
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
55 matching events found
No baseline correction applied
    Stimulus_c75: 55 valid trials out of 55

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

  Loading condition: Stimulus_i25
Adding metadata with 30 columns
43 matching events found
No baseline correction applied
    Stimulus_i25: 43 valid trials out of 43

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

  Loading condition: Stimulus_i75
Adding metadata with 30 columns
164 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 164 valid trials out of 164
Loading data for subject: D0059
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0059/D0059_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0059/D0059_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
161 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 161 valid trials out of 161
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
55 matching events found
No baseline correction applied
    Stimulus_c75: 55 valid trials out of 55

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

  Loading condition: Stimulus_i25
Adding metadata with 30 columns
53 matching events found
No baseline correction applied
    Stimulus_i25: 53 valid trials out of 53

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

  Loading condition: Stimulus_i75
Adding metadata with 30 columns
158 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 158 valid trials out of 158
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
161 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 161 valid trials out of 161
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
55 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 55 valid trials out of 55
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
53 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 53 valid trials out of 53
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
158 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 158 valid trials out of 158
Loading data for subject: D0063
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0063/D0063_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
452 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0063/D0063_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
452 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
165 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 165 valid trials out of 165
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
56 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 56 valid trials out of 56
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
36 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 36 valid trials out of 36
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
132 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 132 valid trials out of 132
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
165 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 165 valid trials out of 165
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
56 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 56 valid trials out of 56
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
36 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 36 valid trials out of 36
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
132 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 132 valid trials out of 132
Loading data for subject: D0065
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0065/D0065_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0065/D0065_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
138 matching events found
No baseline correction applied
    Stimulus_c25: 138 valid trials out of 138

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

  Loading condition: Stimulus_c75
Adding metadata with 30 columns
39 matching events found
No baseline correction applied
    Stimulus_c75: 39 valid trials out of 39
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
28 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)
/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 28 valid trials out of 28
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
111 matching events found
No baseline correction applied
    Stimulus_i75: 111 valid trials out of 111

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
138 matching events found
No baseline correction applied
    Stimulus_c25: 138 valid trials out of 138

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

  Loading condition: Stimulus_c75
Adding metadata with 30 columns
39 matching events found
No baseline correction applied
    Stimulus_c75: 39 valid trials out of 39
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
28 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)
/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 28 valid trials out of 28
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
111 matching events found
No baseline correction applied
    Stimulus_i75: 111 valid trials out of 111

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Loading data for subject: D0069
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0069/D0069_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0069/D0069_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
132 matching events found
No baseline correction applied
    Stimulus_c25: 132 valid trials out of 132

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

  Loading condition: Stimulus_c75
Adding metadata with 30 columns
45 matching events found
No baseline correction applied
    Stimulus_c75: 45 valid trials out of 45
  Loading condition: Stimulus_i25
Adding metadata with 30 columns

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)
/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

33 matching events found
No baseline correction applied
    Stimulus_i25: 33 valid trials out of 33
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
120 matching events found
No baseline correction applied
    Stimulus_i75: 120 valid trials out of 120

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
132 matching events found
No baseline correction applied
    Stimulus_c25: 132 valid trials out of 132

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

  Loading condition: Stimulus_c75
Adding metadata with 30 columns
45 matching events found
No baseline correction applied
    Stimulus_c75: 45 valid trials out of 45
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
33 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)
/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 33 valid trials out of 33
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
120 matching events found
No baseline correction applied
    Stimulus_i75: 120 valid trials out of 120

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Loading data for subject: D0077
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0077/D0077_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0077/D0077_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
137 matching events found
No baseline correction applied
    Stimulus_c25: 137 valid trials out of 137

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

  Loading condition: Stimulus_c75
Adding metadata with 30 columns
49 matching events found
No baseline correction applied
    Stimulus_c75: 49 valid trials out of 49
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
37 matching events found

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)
/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

No baseline correction applied
    Stimulus_i25: 37 valid trials out of 37
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
132 matching events found
No baseline correction applied
    Stimulus_i75: 132 valid trials out of 132

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
137 matching events found
No baseline correction applied
    Stimulus_c25: 137 valid trials out of 137

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

  Loading condition: Stimulus_c75
Adding metadata with 30 columns
49 matching events found
No baseline correction applied
    Stimulus_c75: 49 valid trials out of 49
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
37 matching events found

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)
/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

No baseline correction applied
    Stimulus_i25: 37 valid trials out of 37
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
132 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 132 valid trials out of 132
Loading data for subject: D0090
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0090/D0090_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
450 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0090/D0090_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
450 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
162 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 162 valid trials out of 162
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
52 matching events found
No baseline correction applied
    Stimulus_c75: 52 valid trials out of 52

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

  Loading condition: Stimulus_i25
Adding metadata with 30 columns
56 matching events found
No baseline correction applied
    Stimulus_i25: 56 valid trials out of 56

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

  Loading condition: Stimulus_i75
Adding metadata with 30 columns
157 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 157 valid trials out of 157
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
162 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 162 valid trials out of 162
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
52 matching events found
No baseline correction applied
    Stimulus_c75: 52 valid trials out of 52

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

  Loading condition: Stimulus_i25
Adding metadata with 30 columns
56 matching events found
No baseline correction applied
    Stimulus_i25: 56 valid trials out of 56

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

  Loading condition: Stimulus_i75
Adding metadata with 30 columns
157 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 157 valid trials out of 157
Loading data for subject: D0094
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0094/D0094_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0094/D0094_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
160 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 160 valid trials out of 160
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
49 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 49 valid trials out of 49
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
45 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 45 valid trials out of 45
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
124 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 124 valid trials out of 124
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
160 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 160 valid trials out of 160
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
49 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 49 valid trials out of 49
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
45 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 45 valid trials out of 45
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
124 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 124 valid trials out of 124
Loading data for subject: D0100
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0100/D0100_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
451 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0100/D0100_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
451 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
168 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 168 valid trials out of 168
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
49 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 49 valid trials out of 49
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
56 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 56 valid trials out of 56
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
148 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 148 valid trials out of 148
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
168 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 168 valid trials out of 168
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
49 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 49 valid trials out of 49
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
56 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 56 valid trials out of 56
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
148 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 148 valid trials out of 148
Loading data for subject: D0102
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0102/D0102_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0102/D0102_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
147 matching events found

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

No baseline correction applied
    Stimulus_c25: 147 valid trials out of 147
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
46 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 46 valid trials out of 46
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
26 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 26 valid trials out of 26
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
80 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 80 valid trials out of 80
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
147 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 147 valid trials out of 147
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
46 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 46 valid trials out of 46
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
26 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 26 valid trials out of 26
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
80 matching events found

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

No baseline correction applied
    Stimulus_i75: 80 valid trials out of 80
Loading data for subject: D0103
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0103/D0103_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0103/D0103_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
159 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 159 valid trials out of 159
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
41 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 41 valid trials out of 41
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
46 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 46 valid trials out of 46
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
113 matching events found
No baseline correction applied
    Stimulus_i75: 113 valid trials out of 113
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
159 matching events found
No baseline correction applied
    Stimulus_c25: 159 valid trials out of 159
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
41 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 41 valid trials out of 41
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
46 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 46 valid trials out of 46
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
113 matching events found
No baseline correction applied
    Stimulus_i75: 113 valid trials out of 113
Loading data for subject: D0107A
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0107A/D0107A_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
452 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0107A/D0107A_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
452 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
162 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 162 valid trials out of 162
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
51 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 51 valid trials out of 51
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
44 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 44 valid trials out of 44
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
137 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 137 valid trials out of 137
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
162 matching events found
No baseline correction applied
    Stimulus_c25: 162 valid trials out of 162
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
51 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 51 valid trials out of 51
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
44 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 44 valid trials out of 44
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
137 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 137 valid trials out of 137
Loading data for subject: D0110
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0110/D0110_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0110/D0110_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
164 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 164 valid trials out of 164
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
56 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 56 valid trials out of 56
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
51 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 51 valid trials out of 51
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
168 matching events found
No baseline correction applied
    Stimulus_i75: 168 valid trials out of 168
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
164 matching events found
No baseline correction applied
    Stimulus_c25: 164 valid trials out of 164
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
56 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 56 valid trials out of 56
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
51 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 51 valid trials out of 51
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
168 matching events found
No baseline correction applied
    Stimulus_i75: 168 valid trials out of 168
Loading data for subject: D0116
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0116/D0116_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0116/D0116_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
166 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 166 valid trials out of 166
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
56 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 56 valid trials out of 56
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
41 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 41 valid trials out of 41
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
147 matching events found
No baseline correction applied
    Stimulus_i75: 147 valid trials out of 147
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
166 matching events found
No baseline correction applied
    Stimulus_c25: 166 valid trials out of 166
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
56 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 56 valid trials out of 56
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
41 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 41 valid trials out of 41
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
147 matching events found
No baseline correction applied
    Stimulus_i75: 147 valid trials out of 147
Loading data for subject: D0117
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0117/D0117_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0117/D0117_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
127 matching events found
No baseline correction applied
    Stimulus_c25: 127 valid trials out of 127
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
35 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 35 valid trials out of 35
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
28 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 28 valid trials out of 28
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
93 matching events found
No baseline correction applied
    Stimulus_i75: 93 valid trials out of 93
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
127 matching events found
No baseline correction applied
    Stimulus_c25: 127 valid trials out of 127
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
35 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 35 valid trials out of 35
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
28 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 28 valid trials out of 28
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
93 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 93 valid trials out of 93
Loading data for subject: D0121
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0121/D0121_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0121/D0121_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25
Adding metadata with 30 columns
154 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25: 154 valid trials out of 154
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
52 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 52 valid trials out of 52
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
45 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 45 valid trials out of 45
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
149 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 149 valid trials out of 149
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
154 matching events found
No baseline correction applied
    Stimulus_c25: 154 valid trials out of 154
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
52 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 52 valid trials out of 52
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
45 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 45 valid trials out of 45
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
149 matching events found
No baseline correction applied
    Stimulus_i75: 149 valid trials out of 149
Loading data for subject: D0133
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0133/D0133_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
454 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0133/D0133_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
454 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
150 matching events found
No baseline correction applied
    Stimulus_c25: 150 valid trials out of 150
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
52 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 52 valid trials out of 52
  Loading condition: Stimulus_i25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
42 matching events found
No baseline correction applied
    Stimulus_i25: 42 valid trials out of 42
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
132 matching events found
No baseline correction applied
    Stimulus_i75: 132 valid trials out of 132
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
150 matching events found
No baseline correction applied
    Stimulus_c25: 150 valid trials out of 150
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
52 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 52 valid trials out of 52
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
42 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 42 valid trials out of 42
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
132 matching events found
No baseline correction applied
    Stimulus_i75: 132 valid trials out of 132
Loading data for subject: D0134
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0134/D0134_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
450 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0134/D0134_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
450 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
164 matching events found
No baseline correction applied
    Stimulus_c25: 164 valid trials out of 164
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
56 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 56 valid trials out of 56
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
45 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 45 valid trials out of 45
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
157 matching events found
No baseline correction applied
    Stimulus_i75: 157 valid trials out of 157
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
164 matching events found
No baseline correction applied
    Stimulus_c25: 164 valid trials out of 164
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
56 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 56 valid trials out of 56
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
45 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 45 valid trials out of 45
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
157 matching events found
No baseline correction applied
    Stimulus_i75: 157 valid trials out of 157
Loading data for subject: D0137
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0137/D0137_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 27 columns
455 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 27 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0137/D0137_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 27 columns
455 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 27 columns
Replacing existing metadata with 28 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 28 columns
160 matching events found
No baseline correction applied
    Stimulus_c25: 160 valid trials out of 160
  Loading condition: Stimulus_c75
Adding metadata with 28 columns
57 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 57 valid trials out of 57
  Loading condition: Stimulus_i25
Adding metadata with 28 columns
41 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 41 valid trials out of 41
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 28 columns
153 matching events found
No baseline correction applied
    Stimulus_i75: 153 valid trials out of 153
Replacing existing metadata with 28 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 28 columns
160 matching events found
No baseline correction applied
    Stimulus_c25: 160 valid trials out of 160
  Loading condition: Stimulus_c75
Adding metadata with 28 columns
57 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 57 valid trials out of 57
  Loading condition: Stimulus_i25
Adding metadata with 28 columns
41 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 41 valid trials out of 41
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 28 columns
153 matching events found
No baseline correction applied
    Stimulus_i75: 153 valid trials out of 153
Loading data for subject: D0138
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0138/D0138_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0138/D0138_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
156 matching events found
No baseline correction applied
    Stimulus_c25: 156 valid trials out of 156
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
50 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 50 valid trials out of 50
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
44 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 44 valid trials out of 44
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
149 matching events found
No baseline correction applied
    Stimulus_i75: 149 valid trials out of 149
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
156 matching events found
No baseline correction applied
    Stimulus_c25: 156 valid trials out of 156
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
50 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 50 valid trials out of 50
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
44 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 44 valid trials out of 44
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
149 matching events found
No baseline correction applied
    Stimulus_i75: 149 valid trials out of 149
Loading data for subject: D0139A
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0139A/D0139A_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0139A/D0139A_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
147 matching events found
No baseline correction applied
    Stimulus_c25: 147 valid trials out of 147
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
51 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 51 valid trials out of 51
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
43 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 43 valid trials out of 43
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
145 matching events found
No baseline correction applied
    Stimulus_i75: 145 valid trials out of 145
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
147 matching events found
No baseline correction applied
    Stimulus_c25: 147 valid trials out of 147
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
51 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 51 valid trials out of 51
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
43 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 43 valid trials out of 43
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
145 matching events found
No baseline correction applied
    Stimulus_i75: 145 valid trials out of 145
Loading data for subject: D0144
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0144/D0144_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
450 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0144/D0144_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
450 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
154 matching events found
No baseline correction applied
    Stimulus_c25: 154 valid trials out of 154
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
52 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 52 valid trials out of 52
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
45 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 45 valid trials out of 45
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
162 matching events found
No baseline correction applied
    Stimulus_i75: 162 valid trials out of 162
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
154 matching events found
No baseline correction applied
    Stimulus_c25: 154 valid trials out of 154
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
52 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 52 valid trials out of 52
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
45 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 45 valid trials out of 45
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
162 matching events found
No baseline correction applied
    Stimulus_i75: 162 valid trials out of 162
Loading data for subject: D0145
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0145/D0145_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
452 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0145/D0145_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
452 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
168 matching events found
No baseline correction applied
    Stimulus_c25: 168 valid trials out of 168
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
53 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 52 valid trials out of 53
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
50 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 50 valid trials out of 50
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
138 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 138 valid trials out of 138
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
168 matching events found
No baseline correction applied
    Stimulus_c25: 168 valid trials out of 168
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
53 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 52 valid trials out of 53
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
50 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 50 valid trials out of 50
  Loading condition: Stimulus_i75
Adding metadata with 30 columns
138 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75: 138 valid trials out of 138
Loading data for subject: D0146
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0146/D0146_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0146/D0146_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_1.5s_filterbank_hilbert_stat_func_ttest_zmax_20_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
168 matching events found
No baseline correction applied
    Stimulus_c25: 168 valid trials out of 168
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
56 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 56 valid trials out of 56
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
51 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 51 valid trials out of 51
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
162 matching events found
No baseline correction applied
    Stimulus_i75: 162 valid trials out of 162
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_c25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
168 matching events found
No baseline correction applied
    Stimulus_c25: 168 valid trials out of 168
  Loading condition: Stimulus_c75
Adding metadata with 30 columns
56 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75: 56 valid trials out of 56
  Loading condition: Stimulus_i25
Adding metadata with 30 columns
51 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25: 51 valid trials out of 51
  Loading condition: Stimulus_i75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:663: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
162 matching events found
No baseline correction applied
    Stimulus_i75: 162 valid trials out of 162

--- Summary of Dropped Electrodes ---
Total electrodes dropped across all subjects/ROIs: 0
-------------------------------------

In [9]:
all_electrodes_per_subject_roi

{'lpfc': {'D0057': ['RAI6',
   'RAI12',
   'RAI13',
   'RAI14',
   'RAI15',
   'RAI16',
   'RPI15',
   'RPI14',
   'RAMF10',
   'RAMF11',
   'RAMF12',
   'RAMF13',
   'RAMF14',
   'RAIF11',
   'RAIF12',
   'RAIF13',
   'RAIF14'],
  'D0059': ['LMMF9', 'LMMF11', 'LMMF10', 'LMMF12', 'LPSF16'],
  'D0063': ['LASF10',
   'LASF11',
   'LASF14',
   'LASF15',
   'LASF16',
   'LMSF5',
   'LMSF6',
   'LMSF12',
   'LPSF10',
   'LPSF12',
   'ROF16',
   'RAI16',
   'RAMF11',
   'RAMF12',
   'RAMF13',
   'RAMF14',
   'RMMF13',
   'RMMF14',
   'RAI4',
   'RAI6',
   'RAI5',
   'RAI10',
   'RAI11',
   'RASF15',
   'RASF16',
   'RMSF8',
   'RMSF9',
   'RMSF10',
   'RMSF11',
   'RMSF12',
   'RMSF7',
   'RAMF8',
   'RAMF9',
   'RAMF10',
   'RMMF9',
   'RMMF10'],
  'D0065': ['RASF13',
   'RASF14',
   'RASF15',
   'RASF16',
   'RMSF11',
   'RMSF12',
   'RMSF13',
   'RMSF14',
   'RI7'],
  'D0069': ['LOF8'],
  'D0071': ['RFO14',
   'RFO16',
   'RIA4',
   'RIP6',
   'RIA5',
   'RIA11',
   'RIA12',
   'RIA13',
   'RIA14',
   'RIA16',
   'RIP14',
   'RIP15',
   'RIP16'],
  'D0077': [],
  'D0090': ['RFO15',
   'RIA6',
   'RIA11',
   'RIA12',
   'RIA14',
   'RIA15',
   'RIA16',
   'RIP7'],
  'D0094': ['LFO12',
   'LFO13',
   'LFO15',
   'LFO16',
   'LFAM8',
   'LFAM9',
   'LFAM10',
   'LFAM13',
   'LFAM14',
   'LFPM10',
   'LFPM11',
   'LFPM12',
   'LPAS1',
   'LIA16',
   'LFAI3',
   'LFAI4',
   'LFAI5',
   'LFPI10',
   'LPAI9',
   'LPAI10',
   'LIA4',
   'LIA5',
   'LFAI9',
   'LFAI10',
   'LIA11',
   'LIA12',
   'LIA13',
   'LIA14'],
  'D0100': [],
  'D0102': ['RFO13', 'RFO14', 'RFAM15', 'RFAI2', 'RFAI3'],
  'D0103': ['LFAM8',
   'LFAM9',
   'LAI13',
   'LAI14',
   'LFAM15',
   'LAI4',
   'LAI7',
   'LAI8',
   'LAI18',
   'LFO15',
   'LFAI4'],
  'D0107A': ['RFOA16',
   'RFOA17',
   'RFOA18',
   'RFAI3',
   'RIA5',
   'RIA6',
   'RFAM7',
   'RFAM9',
   'RFAM10',
   'RFAM11',
   'RFAM12',
   'RFMM9',
   'RFMM11',
   'RFMM12',
   'RFMM13',
   'RFMM14',
   'RFMM15',
   'RFMM8',
   'RIA12',
   'RIA13',
   'RIA14',
   'RIA15',
   'RIA16',
   'RIA17',
   'RIA18'],
  'D0110': ['LASF10', 'LOF13', 'LOF15', 'LINS4', 'LINS5'],
  'D0116': ['LFOA14',
   'LFOA17',
   'LFOA18',
   'LFOP15',
   'LFAM10',
   'LFAM11',
   'LFMM14',
   'LAI12',
   'LAI16',
   'LFAM12',
   'LAI7',
   'LAI8',
   'LFMI3',
   'LFMI5',
   'LFMI6',
   'RFOA14',
   'RFOA15',
   'RFOA16',
   'RFOP15',
   'RFMM10',
   'RFMM11',
   'RFMM12',
   'RAI7',
   'RAI11',
   'RAI12',
   'RAI14',
   'RAI15',
   'RAI16',
   'RAI17',
   'RFMI4'],
  'D0117': ['RMOF15',
   'RINSA15',
   'RINSA16',
   'RLOF10',
   'RLOF11',
   'RLOF16',
   'RINSA3',
   'RINSA11',
   'RINSA12',
   'RINSA13',
   'RINSA14'],
  'D0121': ['LFOA15',
   'LFOP12',
   'LFO5',
   'LFO6',
   'LFO8',
   'LFO9',
   'LFO12',
   'LFO13',
   'LFO14',
   'LFO15',
   'LFO16',
   'LFO17',
   'LFO18',
   'LFA1',
   'LFA2',
   'LFP16',
   'LFP17',
   'LFPS1',
   'LFPS2',
   'LFPP1',
   'LFOP13',
   'LFOP15',
   'LFOP16',
   'LFOP18',
   'LFA7',
   'LFA8',
   'LFAS6',
   'LFAM8',
   'LFAM9',
   'LFA9',
   'LFA10',
   'LFA11',
   'LFA12',
   'LFAM10',
   'LFAM11',
   'LFAM12',
   'LFMM8',
   'LFMM9',
   'LFMM10',
   'LFMM11',
   'LFMM12',
   'LFAS7',
   'LFAS8',
   'LFAS9',
   'LFAS10',
   'LFMS7',
   'LFMS9',
   'LFMS10',
   'LFMS11',
   'LFMS12',
   'LFPS6',
   'LFPS7',
   'LFPS9',
   'LFPS10',
   'LFPP7',
   'LFPP9',
   'LFPP10',
   'LFMI4',
   'LFMI5',
   'LFMI8',
   'LFMI9'],
  'D0130': [],
  'D0133': ['LFAA7',
   'LFAA9',
   'LFAA10',
   'LFAA11',
   'LFAI5',
   'LFAI6',
   'LFAI7',
   'LFAI8',
   'LFAI9',
   'LFAI10',
   'LFAM8',
   'LFAP6',
   'LFAP7',
   'LFAP8',
   'LFAP9',
   'LFAP10',
   'LFAI3',
   'LFAI4',
   'LFAM5',
   'LFAM6',
   'LFAM7',
   'LFMM8',
   'LFMM9',
   'LFMM10',
   'LFAP3',
   'LFPA2',
   'RFAL8',
   'RFAL9',
   'RFAL10',
   'RFAL11',
   'RFAL12',
   'RFAM4',
   'RFAM6',
   'RFAM7',
   'RFAM8',
   'RFAM9',
   'RFAM10',
   'RFAM11',
   'RFAM12'],
  'D0134': ['LFAS7',
   'LFAS8',
   'LLeSS9',
   'LFAM4',
   'LLeSS8',
   'LFAM5',
   'LFAM9',
   'LFAM10',
   'LLeSS10',
   'LLeSS11',
   'LLeSM10',
   'LINS9',
   'LINS12',
   'LINS13',
   'LINS14',
   'LINS15',
   'LLeSL8',
   'LLeSL9',
   'LLeSL10',
   'LINS5',
   'LFMEG1',
   'LFMEG2',
   'RFAS5',
   'RFAS6',
   'RFAS7',
   'RFAS8',
   'RFAM14',
   'RINS10',
   'RSFMEG1',
   'RINS6',
   'RINS7',
   'RIFMEG1',
   'RIFMEG2',
   'RIFMEG7',
   'RIFMEG8',
   'RIFMEG9',
   'RIFMEG10',
   'RINS11',
   'RINS12',
   'RINS13'],
  'D0137': ['LAI6', 'LAI7', 'LAI10', 'LAI15', 'LAI17', 'LAI18'],
  'D0138': ['LFAM14',
   'LFAM15',
   'LFAM16',
   'LFAM17',
   'LFAM18',
   'LFOA16',
   'LFOA18',
   'LFOP16',
   'LFOP17',
   'LFOP18',
   'LFOA14',
   'LFOA15',
   'LAI2',
   'LAI3',
   'LAI4',
   'LAI5',
   'LAI13',
   'LAI14',
   'LAI15',
   'LAI16'],
  'D0139A': ['LFOP13',
   'LFOP14',
   'LFOP16',
   'LFOP17',
   'LFOP18',
   'LFAI2',
   'LIA6',
   'LFAI3',
   'LFAI4',
   'LIA13',
   'LIA14',
   'LIA15',
   'LIA16',
   'LIA17'],
  'D0144': ['LOF13',
   'LOF14',
   'LAI10',
   'LAI11',
   'LOF16',
   'LFAI11',
   'LFAI12',
   'LFAI13',
   'LFAI14',
   'LFMM8',
   'LFMM9',
   'LFMM10',
   'LFMM12',
   'LAI13',
   'LAI14',
   'LAI6',
   'LAI7'],
  'D0145': ['RFO10', 'RFO11', 'RFO12', 'RIA10', 'RIA11', 'RIA14', 'LFO10'],
  'D0146': ['LFAM8',
   'LFAM9',
   'LFAM10',
   'LFAM11',
   'LFOA12',
   'LFAM13',
   'LFAM14',
   'LFOA13',
   'LFOA14',
   'LFOA15',
   'LFOA16',
   'LFOP16',
   'LFOP15',
   'LFMI2',
   'LFMI3',
   'LFMI4',
   'LFMI7',
   'LFMI8',
   'LAI10',
   'LAI11',
   'LAI13',
   'LAI14',
   'LAI15']}}

In [12]:
all_elecs_count_per_roi

{'lpfc': 431}

In [ ]:
all_elecs_count_per_roi = {}
sig_elecs_count_per_roi = {}

for roi in rois:
    all_elecs_count_per_roi[roi] = 0
    sig_elecs_count_per_roi[roi] = 0
    
for roi, subjects_elecs in all_electrodes_per_subject_roi.items():
    for sub, elecs in subjects_elecs.items():
        all_elecs_count_per_roi[roi] += len(all_electrodes_per_subject_roi[roi][sub])
    
for roi, subjects_elecs in sig_electrodes_per_subject_roi.items():
    for sub, elecs in subjects_elecs.items():
        sig_elecs_count_per_roi[roi] += len(sig_electrodes_per_subject_roi[roi][sub])
    
for roi in rois:
    print(f'{roi} has {all_elecs_count_per_roi[roi]} elecs')
    print(f'{roi} has {sig_elecs_count_per_roi[roi]} sig elecs')

lpfc has 431 elecs
lpfc has 174 elecs

In [61]:
# ------------------------------------------------------------------
# 3b. Optionally filter electrodes to those flagged in a prior
#     within-electrode ANOVA run.
# ------------------------------------------------------------------

if getattr(args, 'anova_labels_csv', None):
    from src.analysis.utils.anova_label_selection import (
        load_anova_label_electrodes, selected_pairs)
    selection = load_anova_label_electrodes(
        args.anova_labels_csv, effect=args.anova_label_effect,
        correction=args.anova_label_correction, alpha=args.anova_label_alpha,
        roi=args.anova_label_roi)
    keep = selected_pairs(selection)
    for roi_name in rois:
        for sub, elec_list in electrodes[roi_name].items():
            electrodes[roi_name][sub] = [e for e in elec_list if (sub, e) in keep]
    remaining = sum(len(v) for d in electrodes.values() for v in d.values())
    if not remaining:
        raise ValueError("anova_labels.csv selection matched zero loaded electrodes; "
                            "check subject/electrode names, ROI, effect, and correction")
    print(f"[anova-labels] {remaining} electrodes remain for "
            f"{args.anova_label_effect} ({args.anova_label_correction})")

[anova-labels] 3 electrodes remain for lwpc (flags)

In [67]:
# ------------------------------------------------------------------
# 4. Build evokeds for all conditions
# ------------------------------------------------------------------
evks_dict_elecs = make_multi_channel_evokeds_for_all_conditions_and_rois(
    subjects_mne_objects, args.subjects, rois, condition_names, electrodes
)

NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).

In [82]:
# ------------------------------------------------------------------
# 5. Statistical testing
# ------------------------------------------------------------------
significant_clusters = {}
interaction_results = None

if args.statistical_method == 'time_perm_cluster':
    print("\nRunning statistical tests comparing TWO conditions")
    if len(condition_names) != 2:
        raise ValueError("Time perm cluster stats requires exactly two conditions.")

    p_values_dict = {}
    condition1_name, condition2_name = condition_names

    for roi in rois:
        print(f"-- Processing ROI: {roi} --")
        try:
            evoked_cond1_this_roi = evks_dict_elecs[condition1_name][roi]
            evoked_cond2_this_roi = evks_dict_elecs[condition2_name][roi]

            mask_roi, p_values = time_perm_cluster_between_two_evokeds(
                evoked_cond1_this_roi, evoked_cond2_this_roi,
                p_thresh=args.p_thresh_for_time_perm_cluster_stats,
                p_cluster=args.p_cluster, n_perm=args.n_perm,
                tails=args.tails, axis=0, stat_func=args.stat_func,
                ignore_adjacency=None,
                permutation_type=args.permutation_type,
                vectorized=True, n_jobs=args.n_jobs, seed=None, verbose=True,
            )

            significant_clusters[roi] = mask_roi
            p_values_dict[roi] = p_values
        except KeyError:
            print(f"   Skipping ROI {roi}: Missing prepared evoked data for "
                    f"one or both conditions.")

elif args.statistical_method == 'anova':
    # anova_interactions may legitimately be empty (single main-effect ANOVA);
    # we only require at least one factor to run the ANOVA.
    if not anova_factors:
        raise ValueError(
            f"condition_label '{condition_label}' has no 'anova_factors' "
            f"in the registry."
        )

    # Pull a representative evoked to get the full time vector
    ref_evk = next(
        (evks_dict_elecs[c][r] for c in condition_names for r in rois
            if evks_dict_elecs[c][r] is not None and evks_dict_elecs[c][r].data.shape[0] > 0),
        None,
    )
    if ref_evk is None:
        raise RuntimeError("No usable evoked data found for ANOVA path.")
    full_times = ref_evk.times

    windowed_data = process_windowed_data_for_anova(
        subjects_mne_objects, condition_names, rois, args.subjects,
        electrodes, window_size=args.window_size,
        step_size=args.step_size, sampling_rate=args.sampling_rate,
    )

    if args.anova_unit == 'roi':
        print(f"\nRunning across-electrode ANOVA cluster correction across "
                f"{len(rois)} ROI(s) with {args.n_perm} permutations")
        anova_cluster_results, window_centers = run_windowed_anova_cluster_correction(
            windowed_data, conditions, anova_factors, rois, args.subjects,
            electrodes_per_subject_roi=electrodes,
            times=full_times,
            window_size=args.window_size, step_size=args.step_size,
            sampling_rate=args.sampling_rate,
            n_perm=args.n_perm,
            percentile=int(100 * (1 - args.p_thresh_for_time_perm_cluster_stats)),
            cluster_percentile=int(100 * (1 - args.p_cluster)),
            split_clusters_by_sign=args.split_clusters_by_sign,
            seed=42, n_jobs=args.n_jobs, verbose=True,
        )
        # The interaction mega-plot only makes sense for a factorial design;
        # for a single main-effect ANOVA there are no interactions to plot.
        if anova_interactions:
            interaction_results = anova_results_to_interaction_results_for_plotting(
                anova_cluster_results, anova_interactions,
            )
        else:
            interaction_results = None
        within_elec_summary = None
        within_elec_skipped = None

    else:   # 'electrode'
        print(f"\nRunning within-electrode ANOVA cluster correction across "
                f"{len(rois)} ROI(s) with {args.n_perm} permutations")
        run_label = conditions_save_name   # filenames inside the run dir
        (anova_cluster_results, window_centers,
            within_elec_summary, within_elec_skipped) = \
            run_within_electrode_windowed_anova_cluster_correction(
                windowed_data, conditions, anova_factors, rois, args.subjects,
                electrodes_per_subject_roi=electrodes,
                times=full_times,
                window_size=args.window_size, step_size=args.step_size,
                sampling_rate=args.sampling_rate,
                n_perm=args.n_perm,
                percentile=int(100 * (1 - args.p_thresh_for_time_perm_cluster_stats)),
                cluster_percentile=int(100 * (1 - args.p_cluster)),
                min_trials_per_cell=args.min_trials_per_cell,
                split_clusters_by_sign=args.split_clusters_by_sign,
                seed=42, n_jobs=args.n_jobs, verbose=True,
                save_dir=save_dir, run_label=run_label,
            )
        # In within-electrode mode the 16-condition mega-plot doesn't make
        # sense (results are per-electrode, not ROI-aggregated). Skip it.
        interaction_results = None

        # Per-electrode power traces: one subplot per electrode, paginated.
        per_elec_pt_dir = os.path.join(save_dir, 'per_electrode_power_traces')
        os.makedirs(per_elec_pt_dir, exist_ok=True)
        print(f"\nPlotting per-electrode power traces to: {per_elec_pt_dir}")
        plot_per_electrode_power_traces(
            subjects_mne_objects, rois, condition_names,
            electrodes_per_subject_roi=electrodes,
            plotting_parameters=plot_params,
            save_dir=per_elec_pt_dir,
            error='sem',
        )
        plt.close('all')

        # Per-electrode F traces: one subplot per electrode, paginated,
        # one figure per (roi, effect). Reads the per-electrode npz files
        # written by the within-electrode ANOVA above.
        within_run_dir = os.path.join(save_dir, run_label)
        per_elec_f_dir = os.path.join(save_dir, 'per_electrode_F_traces')
        os.makedirs(per_elec_f_dir, exist_ok=True)
        print(f"\nPlotting per-electrode F traces to: {per_elec_f_dir}")
        if within_elec_summary is not None and not within_elec_summary.empty:
            effects = list(within_elec_summary['effect'].unique())
            for roi in rois:
                for effect in effects:
                    plot_per_electrode_F_traces(
                        within_run_dir, roi, effect,
                        save_dir=per_elec_f_dir,
                        sample_window_centers=window_centers,
                    )
                    plt.close('all')
        else:
            print("[per-electrode F traces] no within-electrode summary; "
                    "skipping.")

NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).

Running across-electrode ANOVA cluster correction across 1 ROI(s) with 500 permutations
[anova-cluster] Formula: Activity ~ C(congruency) * C(incongruentProportion)
[anova-cluster] === ROI: lpfc ===

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:   10.1s
[Parallel(n_jobs=-1)]: Done  64 tasks      | elapsed:   28.4s
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:   56.9s
[Parallel(n_jobs=-1)]: Done 280 tasks      | elapsed:  1.7min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  2.7min
[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed:  3.1min finished

create and test cluster mass statistic parameter as either 'extent' (default) or 'sum'

In [ ]:
anova_cluster_results, window_centers = run_windowed_anova_cluster_correction(
    windowed_data, conditions, anova_factors, rois, args.subjects,
    electrodes_per_subject_roi=electrodes,
    times=full_times,
    window_size=args.window_size, step_size=args.step_size,
    sampling_rate=args.sampling_rate,
    n_perm=args.n_perm,
    percentile=int(100 * (1 - args.p_thresh_for_time_perm_cluster_stats)),
    cluster_percentile=int(100 * (1 - args.p_cluster)),
    split_clusters_by_sign=args.split_clusters_by_sign,
    seed=42, n_jobs=args.n_jobs, verbose=True,
)

In [ ]:
rng_master = np.random.RandomState(42)

# Build long dataframe (re-uses your existing function)
df = create_windowed_anova_dataframe(
    windowed_data, conditions, rois, args.subjects,
    electrodes,
    times=full_times, window_size=args.window_size, step_size=args.step_size,
    sampling_rate=args.sampling_rate,
)

# 8/17/26 - keep working through the rest of the code below and put it in here 
# and then try to figure out a way to add the option for cluster mass as a sum rather than extent later

,SubjectID,Electrode,ROI,WindowCenter,WindowIndex,Trial,Activity,BIDS_events,congruency,incongruentProportion
0,D0057,RAI6,lpfc,-0.8750,0,1,0.425460,[Stimulus/c25.0],c,25%
1,D0057,RPI15,lpfc,-0.8750,0,1,0.779750,[Stimulus/c25.0],c,25%
2,D0057,RPI14,lpfc,-0.8750,0,1,0.901805,[Stimulus/c25.0],c,25%
3,D0057,RAI6,lpfc,-0.8125,1,1,0.258035,[Stimulus/c25.0],c,25%
4,D0057,RPI15,lpfc,-0.8125,1,1,0.249346,[Stimulus/c25.0],c,25%
...,...,...,...,...,...,...,...,...,...,...
44950,D0057,RPI15,lpfc,1.3125,35,164,-0.592607,[Stimulus/i75.0],i,75%
44951,D0057,RPI14,lpfc,1.3125,35,164,-0.343914,[Stimulus/i75.0],i,75%
44952,D0057,RAI6,lpfc,1.3750,36,164,-0.059274,[Stimulus/i75.0],i,75%
44953,D0057,RPI15,lpfc,1.3750,36,164,-0.534458,[Stimulus/i75.0],i,75%
44954,D0057,RPI14,lpfc,1.3750,36,164,-0.215213,[Stimulus/i75.0],i,75%

In [ ]:
def run_windowed_anova_cluster_correction(
    windowed_data, conditions_obj, anova_factors, rois, subjects,
    electrodes_per_subject_roi, times, window_size, step_size, sampling_rate,
    n_perm=1000, percentile=95, cluster_percentile=95,
    split_clusters_by_sign=True, cluster_summary_statistic='extent',
    seed=42, n_jobs=-1, verbose=True,
):
    """Run windowed factorial ANOVAs with permutation-based cluster correction.

    For each ROI and time window, this function fits a full-factorial ordinary
    least-squares ANOVA across electrodes. A permutation null distribution is
    generated by shuffling factor labels within each subject-electrode pair,
    using the same shuffle across all windows in a permutation.

    Candidate clusters are formed from consecutive windows whose observed
    F-statistics exceed a window-specific percentile of the permutation null.
    Clusters are corrected using their extent in windows relative to the
    permutation distribution of maximum cluster extents. When requested and
    available, clusters are additionally split at sign changes in the effect's
    signed contrast.

    Parameters
    ----------
    windowed_data : dict
        Windowed data organized as
        ``windowed_data[condition_name][roi][subject_index]``. Each subject
        entry must be an array with shape
        ``(n_trials, n_windows, n_channels)``. Typically the output of
        ``process_windowed_data_for_anova``.
    conditions_obj : dict
        Mapping from condition names in ``windowed_data`` to dictionaries of
        factor values. Each factor named in ``anova_factors`` must be present
        for every included condition.
    anova_factors : sequence of str
        Factor names used to construct the full-factorial ANOVA formula,
        including all main effects and interactions. For example,
        ``['congruency', 'incongruentProportion', 'switchType',
        'switchProportion']``.
    rois : sequence of str
        ROI names to analyze. Names must correspond to keys in the ROI level of
        ``windowed_data``.
    subjects : sequence
        Subject identifiers ordered consistently with the per-subject arrays
        stored in ``windowed_data``.
    electrodes_per_subject_roi : dict
        Electrode metadata used to associate the channel dimension of each
        subject's ROI data with electrode identifiers. Its structure must match
        that expected by ``create_windowed_anova_dataframe``.
    times : array-like of float
        One-dimensional time axis for the original samples. Its length
        determines the length of the returned sample-level masks.
    window_size : int
        Window length in samples.
    step_size : int
        Number of samples between the starts of consecutive windows.
    sampling_rate : float
        Sampling rate of the original data in Hz, used when constructing the
        windowed ANOVA dataframe and window-center time points.
    n_perm : int, default=1000
        Number of label permutations used to estimate the null distributions.
    percentile : float, default=95
        Percentile of the per-window permutation distribution used as the
        cluster-forming threshold. For example, 95 corresponds to a nominal
        pointwise alpha of 0.05.
    cluster_percentile : float, default=95
        Percentile of the permutation distribution of maximum cluster extents
        used as the cluster-level significance threshold. For example, 95
        corresponds to a nominal cluster-corrected alpha of 0.05.
    split_clusters_by_sign : bool, default=True
        If True, split candidate clusters wherever the signed contrast changes
        sign. Sign splitting is applied only when a finite signed contrast can
        be computed for the effect; otherwise, clusters are treated as
        unsigned.
    cluster_summary_statistic : str, default='extent'
        The statistic used to aggregate across a cluster to determine if it's significant or not. Currently supports 'extent' (the total number of windows in the cluster) or 'mass' (the sum of the F values across windows in the cluster).
    seed : int, default=42
        Seed for generating reproducible permutation seeds.
    n_jobs : int, default=-1
        Number of parallel workers passed to ``joblib.Parallel``. A value of
        ``-1`` uses all available processors.
    verbose : bool, default=True
        If True, print the ANOVA formula and analysis progress and enable
        joblib progress output.

    Returns
    -------
    results : dict
        Nested mapping ``results[roi][effect_name]``. Each effect dictionary
        contains:

        ``observed_F`` : numpy.ndarray, shape (n_windows,)
            Observed F-statistic at each window.
        ``null_F`` : numpy.ndarray, shape (n_perm, n_windows)
            Permutation null F-statistics.
        ``signed_contrast`` : numpy.ndarray, shape (n_windows,)
            Signed contrast used for sign-aware cluster splitting. Values may
            be NaN when a signed contrast is unavailable for an effect.
        ``window_mask`` : numpy.ndarray of bool, shape (n_windows,)
            Union of all significant positive, negative, and unsigned clusters.
        ``pos_window_mask`` : numpy.ndarray of bool, shape (n_windows,)
            Windows belonging to significant positive-sign clusters.
        ``neg_window_mask`` : numpy.ndarray of bool, shape (n_windows,)
            Windows belonging to significant negative-sign clusters.
        ``sample_mask`` : numpy.ndarray of bool, shape (len(times),)
            Union window mask expanded onto the original sample time axis.
        ``pos_sample_mask`` : numpy.ndarray of bool, shape (len(times),)
            Positive window mask expanded onto the original sample time axis.
        ``neg_sample_mask`` : numpy.ndarray of bool, shape (len(times),)
            Negative window mask expanded onto the original sample time axis.
        ``sig_clusters_with_sign`` : list of dict
            Significant clusters. Each dictionary contains inclusive ``start``
            and ``end`` window indices, ``sign`` (positive, negative, or zero),
            ``extent`` in windows, and a permutation-based ``p_value``.

        ROIs with no usable data or no successfully fitted windows are omitted.
    window_centers : numpy.ndarray, shape (n_windows,)
        Time coordinate of the center of each analyzed window.

    Notes
    -----
    Cluster mass is implemented here as cluster extent—the number of
    consecutive suprathreshold windows—rather than as the sum of F-statistics.
    A cluster is retained when its extent is strictly greater than the selected
    percentile of the permutation maximum-extent distribution.
    """
    rng_master = np.random.RandomState(seed)

    # Build long dataframe (re-uses your existing function)
    df = create_windowed_anova_dataframe(
        windowed_data, conditions_obj, rois, subjects,
        electrodes_per_subject_roi,
        times=times, window_size=window_size, step_size=step_size,
        sampling_rate=sampling_rate,
    )

    # OLS formula over the requested factors
    formula = 'Activity ~ ' + ' * '.join([f'C({f})' for f in anova_factors])
    if verbose:
        print(f"[anova-cluster] Formula: {formula}")

    # Pre-compute window centers (n_windows,) and the corresponding sample mapping
    window_indices = sorted(df['WindowIndex'].unique())
    n_windows = len(window_indices)
    window_centers = np.array(
        [df[df['WindowIndex'] == w]['WindowCenter'].iloc[0] for w in window_indices]
    )

    # Map each window to a (start_sample, end_sample) range, used to expand
    # window-level clusters back to the full sampling-rate mask for plotting.
    n_times = len(times)
    win_to_samples = []
    for w in window_indices:
        start_sample = int(w * step_size)
        end_sample = min(start_sample + window_size - 1, n_times - 1)
        win_to_samples.append((start_sample, end_sample))

    results = {}

    for roi in rois:
        if verbose:
            print(f"[anova-cluster] === ROI: {roi} ===")
        df_roi = df[df['ROI'] == roi]
        if df_roi.empty:
            continue

        # Aggregate to electrode × window × cell (across-electrode ANOVA)
        group_cols = ['SubjectID', 'Electrode', 'WindowIndex', 'WindowCenter'] + anova_factors
        df_agg = df_roi.groupby(group_cols, as_index=False)['Activity'].mean()

        # === Observed F per effect per window ===
        observed_per_window = {}  # window_idx -> dict(effect -> F)
        for w in window_indices:
            df_w = df_agg[df_agg['WindowIndex'] == w]
            f_dict = _fit_anova_one_window(df_w, formula, anova_factors)
            observed_per_window[w] = f_dict

        # All effects encountered (use first non-None window)
        effect_names = None
        for w in window_indices:
            if observed_per_window[w] is not None:
                effect_names = list(observed_per_window[w].keys())
                break
        if effect_names is None:
            print(f"[anova-cluster] No usable windows for ROI {roi}; skipping.")
            continue

        observed_F = np.full((len(effect_names), n_windows), np.nan)
        for wi, w in enumerate(window_indices):
            f_dict = observed_per_window[w]
            if f_dict is None:
                continue
            for ei, eff in enumerate(effect_names):
                observed_F[ei, wi] = f_dict.get(eff, np.nan)

        # === Compute signed contrast trace per effect alongside observed F ===
        observed_sign = np.full((len(effect_names), n_windows), np.nan)
        if split_clusters_by_sign:
            for wi, w in enumerate(window_indices):
                df_w = df_agg[df_agg['WindowIndex'] == w]
                for ei, eff in enumerate(effect_names):
                    observed_sign[ei, wi] = _signed_contrast_per_window(df_w, eff, anova_factors)

        # === Permutation null ===
        # We shuffle factor labels per electrode once per perm (same shuffle for all windows),
        # since each electrode contributes independent rows per window.
        # Per-perm work: re-fit OLS at every window.
        seeds = rng_master.randint(0, 2**31 - 1, size=n_perm)

        def _one_perm(perm_seed):
            rng = np.random.RandomState(perm_seed)
            shuffle_map = {}
            for (sub, elec), grp in df_agg[df_agg['WindowIndex'] == window_indices[0]] \
                    .groupby(['SubjectID', 'Electrode']):
                n_cells = len(grp)
                shuffle_map[(sub, elec)] = rng.permutation(n_cells)
            null_F_perm = np.full((len(effect_names), n_windows), np.nan)
            null_sign_perm = np.full((len(effect_names), n_windows), np.nan)   # === NEW ===
            for wi, w in enumerate(window_indices):
                df_w = df_agg[df_agg['WindowIndex'] == w].copy().reset_index(drop=True)
                for (sub, elec), idxs in df_w.groupby(['SubjectID', 'Electrode']).groups.items():
                    perm = shuffle_map.get((sub, elec))
                    if perm is None or len(perm) != len(idxs):
                        continue
                    idxs = np.asarray(idxs)
                    for col in anova_factors:
                        df_w.loc[idxs, col] = df_w.loc[idxs[perm], col].values
                f_dict = _fit_anova_one_window(df_w, formula, anova_factors)
                if f_dict is None:
                    continue
                for ei, eff in enumerate(effect_names):
                    null_F_perm[ei, wi] = f_dict.get(eff, np.nan)
                    if split_clusters_by_sign:
                        null_sign_perm[ei, wi] = _signed_contrast_per_window(df_w, eff, anova_factors)
            return null_F_perm, null_sign_perm                                  # === CHANGED ===

        # === unpack tuples from joblib ===
        perm_results = Parallel(n_jobs=n_jobs, verbose=5 if verbose else 0)(
            delayed(_one_perm)(s) for s in seeds
        )
        null_F   = np.stack([r[0] for r in perm_results], axis=0)   # (n_perm, n_effects, n_windows)
        null_sign = np.stack([r[1] for r in perm_results], axis=0)  # same shape

        # === Per-effect sign-aware cluster correction ===
        results[roi] = {}
        for ei, eff in enumerate(effect_names):
            obs    = np.nan_to_num(observed_F[ei], nan=0.0)
            null   = np.nan_to_num(null_F[:, ei, :], nan=0.0)
            obs_sg = observed_sign[ei]                  # may be all NaN for 3-way+
            null_sg = null_sign[:, ei, :] if split_clusters_by_sign else None

            # 1. Per-window pointwise threshold from the null distribution
            pointwise_thresh = np.nanpercentile(null, percentile, axis=0)  # (n_windows,)

            # 2. Raw observed clusters (contiguous windows above threshold)
            above_thresh = obs > pointwise_thresh
            raw_obs_clusters = _find_contiguous_runs(above_thresh)

            # Branch: do we have a usable sign trace?
            do_split = (split_clusters_by_sign and np.any(np.isfinite(obs_sg)))

            if do_split:
                obs_split = _split_clusters_at_sign_flips(raw_obs_clusters, obs_sg)
            else:
                obs_split = [{'start': s, 'end': e, 'sign': 0} for s, e in raw_obs_clusters]

            # 3. Null cluster-mass distribution -- split nulls the SAME way
            null_max_masses = []
            for pi in range(null.shape[0]):
                above_pi = null[pi] > pointwise_thresh
                raw_pi = _find_contiguous_runs(above_pi)
                if do_split:
                    sub_pi = _split_clusters_at_sign_flips(raw_pi, null_sg[pi])
                else:
                    sub_pi = [{'start': s, 'end': e, 'sign': 0} for s, e in raw_pi]
                extents_pi = [c['end'] - c['start'] + 1 for c in sub_pi] or [0]
                null_max_masses.append(max(extents_pi))   # rename to null_max_extents if you want clarity
            null_max_masses = np.array(null_max_masses)
            mass_thresh = np.percentile(null_max_masses, cluster_percentile)

            # 4. Filter observed sub-clusters by mass and compute p per cluster
            sig_subs = []
            for c in obs_split:
                m = c['end'] - c['start'] + 1   # cluster extent in windows
                p = float((null_max_masses >= m).mean())
                if m > mass_thresh:
                    sig_subs.append({**c, 'extent': m, 'p_value': p})

            # 5. Build masks for plotting -- split into pos / neg if sign-aware
            window_mask = np.zeros(n_windows, dtype=bool)
            pos_window_mask = np.zeros(n_windows, dtype=bool)
            neg_window_mask = np.zeros(n_windows, dtype=bool)
            for c in sig_subs:
                window_mask[c['start']:c['end'] + 1] = True
                if c['sign'] > 0:
                    pos_window_mask[c['start']:c['end'] + 1] = True
                elif c['sign'] < 0:
                    neg_window_mask[c['start']:c['end'] + 1] = True

            # 6. Expand window-level masks to sample-level (for time-axis plots)
            def _expand(mask_w):
                m = np.zeros(n_times, dtype=bool)
                for s, e in _find_contiguous_runs(mask_w):
                    sa, _ = win_to_samples[s]
                    _, eb = win_to_samples[e]
                    m[sa:eb + 1] = True
                return m

            results[roi][eff] = {
                'observed_F': observed_F[ei],
                'null_F':     null_F[:, ei, :],
                'signed_contrast':  obs_sg,              # (n_windows,) -- the Δ trace
                'window_mask':      window_mask,          # union (back-compat)
                'pos_window_mask':  pos_window_mask,
                'neg_window_mask':  neg_window_mask,
                'sample_mask':      _expand(window_mask),
                'pos_sample_mask':  _expand(pos_window_mask),
                'neg_sample_mask':  _expand(neg_window_mask),
                'sig_clusters_with_sign': sig_subs,       # list of dicts
            }

    return results, window_centers

old code below

In [12]:
LAB_root = None  # auto-detect below
TASK = 'GlobalLocal'

# SUBJECTS = ['D0103']  # start with one subject for speed; expand later
SUBJECTS = ['D0057', 'D0059', 'D0063', 'D0065', 'D0069', 'D0071', 'D0077', 'D0090', 'D0094', 'D0100', 'D0102', 'D0103', 'D0107A', 'D0110', 'D0116', 'D0117', 'D0121', 'D0133', 'D0134']

ACC_TRIALS_ONLY = False
N_JOBS = 4

CONDITION_LABEL = 'stimulus_lwps_conditions'

# EPOCHS_ROOT_FILE = "Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_thresh_perc_5.0_70.0-150.0_Hz_padLength_0.5s_stat_func_ttest_ind_equal_var_False_nan_policy_omit"
EPOCHS_ROOT_FILE = "Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_thresh_perc_5.0_4.0-8.0_Hz_padLength_1.5s_bandpass_stat_func_ttest_ind_equal_var_False_nan_policy_omit"
EPOCHS_ROOT_FILE = "Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_thresh_perc_5.0_13.0-30.0_Hz_padLength_1.5s_bandpass_stat_func_ttest_ind_equal_var_False_nan_policy_omit"

ROIS_DICT = {
    'lpfc': ["G_front_inf-Opercular", "G_front_inf-Orbital", "G_front_inf-Triangul",
             "G_front_middle", "G_front_sup", "Lat_Fis-ant-Horizont",
             "Lat_Fis-ant-Vertical", "S_circular_insula_ant", "S_circular_insula_sup",
             "S_front_inf", "S_front_middle", "S_front_sup"],
}

ELECTRODES = 'sig'
SAMPLING_RATE = 256
WINDOW_SIZE = 64
STEP_SIZE = 16
N_PERM = 100  # small for sandbox testing; bump to 1000 for the real run
anova_type = 'across_electrode'

In [13]:
if LAB_root is None:
    HOME = os.path.expanduser("~")
    USER = os.path.basename(HOME)
    if os.name == 'nt':
        LAB_root = os.path.join(HOME, "Box", "CoganLab")
    elif sys.platform == 'darwin':
        LAB_root = os.path.join(HOME, "Library", "CloudStorage", "Box-Box", "CoganLab")
    else:
        LAB_root = f"/cwork/{USER}" if os.path.exists(f"/cwork/{USER}") else os.path.join(HOME, "CoganLab")
print("LAB_root:", LAB_root)

LAB_root: /cwork/jz421

In [14]:
conditions = get_conditions_obj(CONDITION_LABEL)
condition_names = list(conditions.keys())
condition_comparisons = get_comparisons(CONDITION_LABEL)
subtraction_pairs = get_subtraction_pairs(CONDITION_LABEL)
anova_factors = get_anova_factors(CONDITION_LABEL)
anova_interactions = get_anova_interactions(CONDITION_LABEL)

print("Number of conditions:", len(conditions))
print("Condition names (first 4):", condition_names[:4])
print("ANOVA factors:", anova_factors)
print("Comparisons:", condition_comparisons)
print("Subtraction pairs:", subtraction_pairs)
print("Interactions:")
for i in anova_interactions:
    print("  ", i['name'], "->", i['factors'])

Number of conditions: 4
Condition names (first 4): ['Stimulus_s25', 'Stimulus_s75', 'Stimulus_r25', 'Stimulus_r75']
ANOVA factors: ['switchType', 'switchProportion']
Comparisons: {'s25_vs_r25': ['s25', 'r25'], 's75_vs_r75': ['s75', 'r75'], 's25_vs_r75': ['s25', 'r75'], 's75_vs_r25': ['s75', 'r25'], 's25_vs_s75': ['s25', 's75'], 'r25_vs_r75': ['r25', 'r75']}
Subtraction pairs: [('Stimulus_s75', 'Stimulus_r75'), ('Stimulus_s25', 'Stimulus_r25')]
Interactions:
   switchType_x_switchProportion -> ['switchType', 'switchProportion']

In [15]:
config_dir = os.path.join(project_root, 'src', 'analysis', 'config')
subjects_electrodestoROIs_dict = utils.make_or_load_subjects_electrodes_to_ROIs_dict(
    subjects=SUBJECTS, save_dir=config_dir,
    filename='subjects_electrodestoROIs_dict.json',
)

sig_chans_per_subject = utils.get_sig_chans_per_subject(
    SUBJECTS, EPOCHS_ROOT_FILE, task=TASK, LAB_root=LAB_root,
)

rois = list(ROIS_DICT.keys())
all_electrodes_per_subject_roi, sig_electrodes_per_subject_roi = \
    utils.make_sig_electrodes_per_subject_and_roi_dict(
        ROIS_DICT, subjects_electrodestoROIs_dict, sig_chans_per_subject,
    )

print("rois:", rois)
print("Per-ROI electrode counts (sig):")
for r in rois:
    for s in SUBJECTS:
        print(f"  {r} / {s}: {len(sig_electrodes_per_subject_roi[r].get(s, []))} sig elecs")

Attempting to load the subjects' electrodes-to-ROIs dictionary...
Loaded data from /hpc/group/coganlab/jz421/GlobalLocal/src/analysis/config/subjects_electrodestoROIs_dict.json
Dictionary loaded successfully. Ready to proceed!
Loaded significant channels for subject D0057
Loaded significant channels for subject D0059
Loaded significant channels for subject D0063
Loaded significant channels for subject D0065
Loaded significant channels for subject D0069
Loaded significant channels for subject D0071
Loaded significant channels for subject D0077
Loaded significant channels for subject D0090
Loaded significant channels for subject D0094
Loaded significant channels for subject D0100
Loaded significant channels for subject D0102
Loaded significant channels for subject D0103
Loaded significant channels for subject D0107A
Loaded significant channels for subject D0110
Loaded significant channels for subject D0116
Loaded significant channels for subject D0117
Loaded significant channels for subject D0121
Loaded significant channels for subject D0133
Loaded significant channels for subject D0134
For subject D0057, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['RAI6', 'RAI12', 'RAI13', 'RAI14', 'RAI15', 'RAI16', 'RPI15', 'RPI14', 'RAMF10', 'RAMF11', 'RAMF12', 'RAMF13', 'RAMF14', 'RAIF11', 'RAIF12', 'RAIF13', 'RAIF14']
For subject D0059, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LMMF9', 'LMMF11', 'LMMF10', 'LMMF12', 'LPSF16']
For subject D0063, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LASF10', 'LASF11', 'LASF14', 'LASF15', 'LASF16', 'LMSF5', 'LMSF6', 'LMSF12', 'LPSF10', 'LPSF12', 'ROF16', 'RAI16', 'RAMF11', 'RAMF12', 'RAMF13', 'RAMF14', 'RMMF13', 'RMMF14', 'RAI4', 'RAI6', 'RAI5', 'RAI10', 'RAI11', 'RASF15', 'RASF16', 'RMSF8', 'RMSF9', 'RMSF10', 'RMSF11', 'RMSF12', 'RMSF7', 'RAMF8', 'RAMF9', 'RAMF10', 'RMMF9', 'RMMF10']
For subject D0065, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['RASF13', 'RASF14', 'RASF15', 'RASF16', 'RMSF11', 'RMSF12', 'RMSF13', 'RMSF14', 'RI7']
For subject D0069, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LOF8']
For subject D0071, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['RFO14', 'RFO16', 'RIA4', 'RIP6', 'RIA5', 'RIA11', 'RIA12', 'RIA13', 'RIA14', 'RIA16', 'RIP14', 'RIP15', 'RIP16']
For subject D0077, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: []
For subject D0090, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['RFO15', 'RIA6', 'RIA11', 'RIA12', 'RIA14', 'RIA15', 'RIA16', 'RIP7']
For subject D0094, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LFO12', 'LFO13', 'LFO15', 'LFO16', 'LFAM8', 'LFAM9', 'LFAM10', 'LFAM13', 'LFAM14', 'LFPM10', 'LFPM11', 'LFPM12', 'LPAS1', 'LIA16', 'LFAI3', 'LFAI4', 'LFAI5', 'LFPI10', 'LPAI9', 'LPAI10', 'LIA4', 'LIA5', 'LFAI9', 'LFAI10', 'LIA11', 'LIA12', 'LIA13', 'LIA14']
For subject D0100, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: []
For subject D0102, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['RFO13', 'RFO14', 'RFAM15', 'RFAI2', 'RFAI3']
For subject D0103, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LFAM8', 'LFAM9', 'LAI13', 'LAI14', 'LFAM15', 'LAI4', 'LAI7', 'LAI8', 'LAI18', 'LFO15', 'LFAI4']
For subject D0107A, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['RFOA16', 'RFOA17', 'RFOA18', 'RFAI3', 'RIA5', 'RIA6', 'RFAM7', 'RFAM9', 'RFAM10', 'RFAM11', 'RFAM12', 'RFMM9', 'RFMM11', 'RFMM12', 'RFMM13', 'RFMM14', 'RFMM15', 'RFMM8', 'RIA12', 'RIA13', 'RIA14', 'RIA15', 'RIA16', 'RIA17', 'RIA18']
For subject D0110, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LASF10', 'LOF13', 'LOF15', 'LINS4', 'LINS5']
For subject D0116, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LFOA14', 'LFOA17', 'LFOA18', 'LFOP15', 'LFAM10', 'LFAM11', 'LFMM14', 'LAI12', 'LAI16', 'LFAM12', 'LAI7', 'LAI8', 'LFMI3', 'LFMI5', 'LFMI6', 'RFOA14', 'RFOA15', 'RFOA16', 'RFOP15', 'RFMM10', 'RFMM11', 'RFMM12', 'RAI7', 'RAI11', 'RAI12', 'RAI14', 'RAI15', 'RAI16', 'RAI17', 'RFMI4']
For subject D0117, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['RMOF15', 'RINSA15', 'RINSA16', 'RLOF10', 'RLOF11', 'RLOF16', 'RINSA3', 'RINSA11', 'RINSA12', 'RINSA13', 'RINSA14']
For subject D0121, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LFOA15', 'LFOP12', 'LFO5', 'LFO6', 'LFO8', 'LFO9', 'LFO12', 'LFO13', 'LFO14', 'LFO15', 'LFO16', 'LFO17', 'LFO18', 'LFA1', 'LFA2', 'LFP16', 'LFP17', 'LFPS1', 'LFPS2', 'LFPP1', 'LFOP13', 'LFOP15', 'LFOP16', 'LFOP18', 'LFA7', 'LFA8', 'LFAS6', 'LFAM8', 'LFAM9', 'LFA9', 'LFA10', 'LFA11', 'LFA12', 'LFAM10', 'LFAM11', 'LFAM12', 'LFMM8', 'LFMM9', 'LFMM10', 'LFMM11', 'LFMM12', 'LFAS7', 'LFAS8', 'LFAS9', 'LFAS10', 'LFMS7', 'LFMS9', 'LFMS10', 'LFMS11', 'LFMS12', 'LFPS6', 'LFPS7', 'LFPS9', 'LFPS10', 'LFPP7', 'LFPP9', 'LFPP10', 'LFMI4', 'LFMI5', 'LFMI8', 'LFMI9']
For subject D0130, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: []
For subject D0133, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LFAA7', 'LFAA9', 'LFAA10', 'LFAA11', 'LFAI5', 'LFAI6', 'LFAI7', 'LFAI8', 'LFAI9', 'LFAI10', 'LFAM8', 'LFAP6', 'LFAP7', 'LFAP8', 'LFAP9', 'LFAP10', 'LFAI3', 'LFAI4', 'LFAM5', 'LFAM6', 'LFAM7', 'LFMM8', 'LFMM9', 'LFMM10', 'LFAP3', 'LFPA2', 'RFAL8', 'RFAL9', 'RFAL10', 'RFAL11', 'RFAL12', 'RFAM4', 'RFAM6', 'RFAM7', 'RFAM8', 'RFAM9', 'RFAM10', 'RFAM11', 'RFAM12']
For subject D0134, G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes are: ['LFAS7', 'LFAS8', 'LLeSS9', 'LFAM4', 'LLeSS8', 'LFAM5', 'LFAM9', 'LFAM10', 'LLeSS10', 'LLeSS11', 'LLeSM10', 'LINS9', 'LINS12', 'LINS13', 'LINS14', 'LINS15', 'LLeSL8', 'LLeSL9', 'LLeSL10', 'LINS5', 'LFMEG1', 'LFMEG2', 'RFAS5', 'RFAS6', 'RFAS7', 'RFAS8', 'RFAM14', 'RINS10', 'RSFMEG1', 'RINS6', 'RINS7', 'RIFMEG1', 'RIFMEG2', 'RIFMEG7', 'RIFMEG8', 'RIFMEG9', 'RIFMEG10', 'RINS11', 'RINS12', 'RINS13']
Subject D0057 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['RAI6', 'RAI12', 'RAI13', 'RAI14', 'RAI15', 'RAI16', 'RPI15', 'RPI14', 'RAMF10', 'RAMF11', 'RAMF12', 'RAIF11', 'RAIF12']
Subject D0059 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: []
Subject D0063 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LASF10', 'LASF11', 'LASF14', 'LASF15', 'LASF16', 'LMSF5', 'LMSF6', 'LMSF12', 'RAI10', 'RMSF8']
Subject D0065 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: []
Subject D0069 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: []
Subject D0071 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['RFO14', 'RIA4', 'RIP6', 'RIA5', 'RIA11', 'RIA12', 'RIA13', 'RIA16', 'RIP14']
Subject D0077 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: []
Subject D0090 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['RFO15', 'RIA6', 'RIA14', 'RIA16']
Subject D0094 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LIA11', 'LIA14']
Subject D0100 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: []
Subject D0102 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: []
Subject D0103 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LAI7', 'LAI8']
Subject D0107A significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['RFMM9']
Subject D0110 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: []
Subject D0116 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LFOA14', 'LFOA17', 'LFOA18', 'LAI16', 'LFMI6', 'RFOA15', 'RAI11', 'RFMI4']
Subject D0117 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: []
Subject D0121 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LFMI5', 'LFMI8']
Subject D0130 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: []
Subject D0133 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['RFAM12']
Subject D0134 significant G_front_inf-Opercular, G_front_inf-Orbital, G_front_inf-Triangul, G_front_middle, G_front_sup, Lat_Fis-ant-Horizont, Lat_Fis-ant-Vertical, S_circular_insula_ant, S_circular_insula_sup, S_front_inf, S_front_middle, S_front_sup electrodes: ['LFAS7', 'LFAS8', 'LLeSS8', 'LFAM5', 'LINS12', 'LINS13', 'LINS14', 'LINS15', 'LLeSL8', 'RFAS5', 'RFAS7', 'RFAS8', 'RFAM14', 'RINS10', 'RIFMEG1', 'RIFMEG2', 'RIFMEG8', 'RIFMEG9', 'RIFMEG10', 'RINS12', 'RINS13']
rois: ['lpfc']
Per-ROI electrode counts (sig):
  lpfc / D0057: 13 sig elecs
  lpfc / D0059: 0 sig elecs
  lpfc / D0063: 10 sig elecs
  lpfc / D0065: 0 sig elecs
  lpfc / D0069: 0 sig elecs
  lpfc / D0071: 9 sig elecs
  lpfc / D0077: 0 sig elecs
  lpfc / D0090: 4 sig elecs
  lpfc / D0094: 2 sig elecs
  lpfc / D0100: 0 sig elecs
  lpfc / D0102: 0 sig elecs
  lpfc / D0103: 2 sig elecs
  lpfc / D0107A: 1 sig elecs
  lpfc / D0110: 0 sig elecs
  lpfc / D0116: 8 sig elecs
  lpfc / D0117: 0 sig elecs
  lpfc / D0121: 2 sig elecs
  lpfc / D0133: 1 sig elecs
  lpfc / D0134: 21 sig elecs

In [11]:
for roi in rois:
    print(f'total sig elecs in {roi}:', sum([len(sig_electrodes_per_subject_roi[roi][sub]) for sub in sig_electrodes_per_subject_roi[roi]]))

total sig elecs in lpfc: 188

In [7]:
subjects_mne_objects = utils.create_subjects_mne_objects_dict(
    subjects=SUBJECTS, epochs_root_file=EPOCHS_ROOT_FILE,
    conditions=conditions, task=TASK,
    just_HG_ev1_rescaled=True, acc_trials_only=ACC_TRIALS_ONLY,
)

# Inspect: what's in there?
sub0 = SUBJECTS[0]
cond0 = condition_names[0]
print("Top-level keys per subject:", list(subjects_mne_objects[sub0].keys())[:5], "...")
print(f"Per-condition keys ({sub0}/{cond0}):",
      list(subjects_mne_objects[sub0][cond0].keys()))
epochs0 = subjects_mne_objects[sub0][cond0]['HG_ev1_power_rescaled']
print("Epochs shape:", epochs0.get_data().shape, "(n_trials, n_channels, n_times)")
print("Times:", epochs0.times[0], "→", epochs0.times[-1], f"({len(epochs0.times)} samples)")

Loading data for subject: D0103
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0103/D0103_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_thresh_perc_5.0_70.0-150.0_Hz_padLength_0.5s_stat_func_ttest_ind_equal_var_False_nan_policy_omit_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0103/D0103_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_thresh_perc_5.0_70.0-150.0_Hz_padLength_0.5s_stat_func_ttest_ind_equal_var_False_nan_policy_omit_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_i25s25

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
3 matching events found
No baseline correction applied
    Stimulus_i25s25: 3 valid trials out of 3
  Loading condition: Stimulus_i25s75
Adding metadata with 30 columns
20 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25s75: 20 valid trials out of 20
  Loading condition: Stimulus_i75s25
Adding metadata with 30 columns
20 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75s25: 20 valid trials out of 20
  Loading condition: Stimulus_i75s75
Adding metadata with 30 columns
64 matching events found

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

No baseline correction applied
    Stimulus_i75s75: 64 valid trials out of 64
  Loading condition: Stimulus_i25r25
Adding metadata with 30 columns
25 matching events found

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

No baseline correction applied
    Stimulus_i25r25: 25 valid trials out of 25
  Loading condition: Stimulus_i25r75
Adding metadata with 30 columns
7 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25r75: 7 valid trials out of 7
  Loading condition: Stimulus_i75r25
Adding metadata with 30 columns
63 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75r25: 63 valid trials out of 63
  Loading condition: Stimulus_i75r75
Adding metadata with 30 columns
19 matching events found

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

No baseline correction applied
    Stimulus_i75r75: 19 valid trials out of 19
  Loading condition: Stimulus_c25s25
Adding metadata with 30 columns
24 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25s25: 24 valid trials out of 24
  Loading condition: Stimulus_c25s75

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

Adding metadata with 30 columns
63 matching events found
No baseline correction applied
    Stimulus_c25s75: 63 valid trials out of 63
  Loading condition: Stimulus_c75s25
Adding metadata with 30 columns
7 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75s25: 7 valid trials out of 7
  Loading condition: Stimulus_c75s75
Adding metadata with 30 columns
19 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75s75: 19 valid trials out of 19
  Loading condition: Stimulus_c25r25
Adding metadata with 30 columns
59 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25r25: 59 valid trials out of 59
  Loading condition: Stimulus_c25r75
Adding metadata with 30 columns
21 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25r75: 21 valid trials out of 21
  Loading condition: Stimulus_c75r25
Adding metadata with 30 columns
21 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75r25: 21 valid trials out of 21
  Loading condition: Stimulus_c75r75
Adding metadata with 30 columns
9 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75r75: 9 valid trials out of 9
Replacing existing metadata with 30 columns
  Loading condition: Stimulus_i25s25
Adding metadata with 30 columns
3 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25s25: 3 valid trials out of 3
  Loading condition: Stimulus_i25s75
Adding metadata with 30 columns
20 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25s75: 20 valid trials out of 20
  Loading condition: Stimulus_i75s25
Adding metadata with 30 columns
20 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75s25: 20 valid trials out of 20
  Loading condition: Stimulus_i75s75
Adding metadata with 30 columns
64 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75s75: 64 valid trials out of 64
  Loading condition: Stimulus_i25r25
Adding metadata with 30 columns
25 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25r25: 25 valid trials out of 25
  Loading condition: Stimulus_i25r75
Adding metadata with 30 columns
7 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i25r75: 7 valid trials out of 7
  Loading condition: Stimulus_i75r25
Adding metadata with 30 columns
63 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75r25: 63 valid trials out of 63
  Loading condition: Stimulus_i75r75
Adding metadata with 30 columns
19 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_i75r75: 19 valid trials out of 19
  Loading condition: Stimulus_c25s25
Adding metadata with 30 columns
24 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25s25: 24 valid trials out of 24
  Loading condition: Stimulus_c25s75
Adding metadata with 30 columns
63 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25s75: 63 valid trials out of 63
  Loading condition: Stimulus_c75s25
Adding metadata with 30 columns
7 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75s25: 7 valid trials out of 7
  Loading condition: Stimulus_c75s75
Adding metadata with 30 columns
19 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75s75: 19 valid trials out of 19
  Loading condition: Stimulus_c25r25
Adding metadata with 30 columns
59 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25r25: 59 valid trials out of 59
  Loading condition: Stimulus_c25r75
Adding metadata with 30 columns
21 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c25r75: 21 valid trials out of 21
  Loading condition: Stimulus_c75r25
Adding metadata with 30 columns
21 matching events found
No baseline correction applied

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

    Stimulus_c75r25: 21 valid trials out of 21
  Loading condition: Stimulus_c75r75
Adding metadata with 30 columns
9 matching events found
No baseline correction applied
    Stimulus_c75r75: 9 valid trials out of 9
Top-level keys per subject: ['Stimulus_i25s25', 'Stimulus_i25s75', 'Stimulus_i75s25', 'Stimulus_i75s75', 'Stimulus_i25r25'] ...
Per-condition keys (D0103/Stimulus_i25s25): ['HG_ev1_rescaled', 'HG_ev1_rescaled_avg', 'HG_ev1_rescaled_std_err', 'HG_ev1_power_rescaled', 'HG_ev1_power_rescaled_avg', 'HG_ev1_power_rescaled_std_err']
Epochs shape: (3, 222, 641) (n_trials, n_channels, n_times)
Times: -1.0 → 1.5 (641 samples)

/hpc/group/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:511: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs_list)

In [8]:
if ELECTRODES == 'all':
    raw_electrodes = all_electrodes_per_subject_roi
    elec_string_to_add_to_filename = 'all_elecs'
else:
    raw_electrodes = sig_electrodes_per_subject_roi
    elec_string_to_add_to_filename = 'sig_elecs'

electrodes = utils.filter_electrode_lists_against_subjects_mne_objects(
    rois, raw_electrodes, subjects_mne_objects,
)

dropped, _ = utils.find_difference_between_two_electrode_lists(raw_electrodes, electrodes)
total_dropped = sum(len(v) for d in dropped.values() for v in d.values())
print(f"Total dropped electrodes: {total_dropped}")
print("Final electrodes per ROI per subject:")
for r in rois:
    for s in SUBJECTS:
        print(f"  {r} / {s}: {len(electrodes[r].get(s, []))} electrodes")

Total dropped electrodes: 0
Final electrodes per ROI per subject:
  lpfc / D0103: 9 electrodes

In [9]:
evks_dict_elecs = make_multi_channel_evokeds_for_all_conditions_and_rois(
    subjects_mne_objects, SUBJECTS, rois, condition_names, electrodes,
)

# Inspect
roi0 = rois[0]
cond0 = condition_names[0]
evk = evks_dict_elecs[cond0][roi0]
print(f"Evoked for {cond0} / {roi0}:")
print(f"  data shape: {evk.data.shape}  (n_electrodes, n_times)")
print(f"  ch_names (first 3): {evk.ch_names[:3]}")
print(f"  times: {evk.times[0]:.3f} → {evk.times[-1]:.3f}")

NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).

NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
Evoked for Stimulus_i25s25 / lpfc:
  data shape: (9, 641)  (n_electrodes, n_times)
  ch_names (first 3): ['LFAM8', 'LFAM9', 'LAI13']
  times: -1.000 → 1.500

In [10]:
windowed_data = process_windowed_data_for_anova(
    subjects_mne_objects, condition_names, rois, SUBJECTS,
    electrodes, window_size=WINDOW_SIZE,
    step_size=STEP_SIZE, sampling_rate=SAMPLING_RATE,
)

# Inspect
arr0 = windowed_data[cond0][roi0][0]  # subject 0
print(f"windowed_data[{cond0}][{roi0}][sub0] shape:")
print(f"  {arr0.shape}  (n_trials, n_windows, n_channels)")
n_windows_expected = (len(evk.times) - WINDOW_SIZE) // STEP_SIZE + 1
print(f"  expected n_windows: {n_windows_expected}")

NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
windowed_data[Stimulus_i25s25][lpfc][sub0] shape:
  (3, 37, 9)  (n_trials, n_windows, n_channels)
  expected n_windows: 37

In [11]:
ref_evk = next(
    (evks_dict_elecs[c][r] for c in condition_names for r in rois
     if evks_dict_elecs[c][r] is not None and evks_dict_elecs[c][r].data.shape[0] > 0),
    None,
)

full_times = ref_evk.times

df = create_windowed_anova_dataframe(
    windowed_data, conditions, rois, electrodes_per_subject_roi=electrodes, subjects=SUBJECTS,
    times=full_times, window_size=WINDOW_SIZE,
    step_size=STEP_SIZE, sampling_rate=SAMPLING_RATE,
)

print("DataFrame shape:", df.shape)
print("Columns:", df.columns.tolist())
print("\nHead:")
df.head()

DataFrame shape: (147852, 12)
Columns: ['SubjectID', 'Electrode', 'ROI', 'WindowCenter', 'WindowIndex', 'Trial', 'Activity', 'BIDS_events', 'congruency', 'congruencyProportion', 'switchType', 'switchProportion']

Head:

,SubjectID,Electrode,ROI,WindowCenter,WindowIndex,Trial,Activity,BIDS_events,congruency,congruencyProportion,switchType,switchProportion
0,D0103,LFAM8,lpfc,-0.875,0,1,-0.116866,[Stimulus/i25.0/s25.0],i,75%,s,25%
1,D0103,LFAM9,lpfc,-0.875,0,1,0.212812,[Stimulus/i25.0/s25.0],i,75%,s,25%
2,D0103,LAI13,lpfc,-0.875,0,1,-0.716582,[Stimulus/i25.0/s25.0],i,75%,s,25%
3,D0103,LAI14,lpfc,-0.875,0,1,-0.077901,[Stimulus/i25.0/s25.0],i,75%,s,25%
4,D0103,LAI4,lpfc,-0.875,0,1,0.353719,[Stimulus/i25.0/s25.0],i,75%,s,25%

In [12]:
data_for_anova = []

# Window centers
if WINDOW_SIZE is not None:
    n_windows = (len(full_times) - WINDOW_SIZE) // STEP_SIZE + 1
    window_centers = []
    for i in range(n_windows):
        start_idx = i * STEP_SIZE
        center_idx = start_idx + WINDOW_SIZE // 2
        if center_idx < len(full_times):
            window_centers.append(full_times[center_idx])
        else:
            window_centers.append(full_times[-1])
else:
    window_centers = [np.mean(full_times)]
    
window_centers

[np.float64(-0.875),
 np.float64(-0.8125),
 np.float64(-0.75),
 np.float64(-0.6875),
 np.float64(-0.625),
 np.float64(-0.5625),
 np.float64(-0.5),
 np.float64(-0.4375),
 np.float64(-0.375),
 np.float64(-0.3125),
 np.float64(-0.25),
 np.float64(-0.1875),
 np.float64(-0.125),
 np.float64(-0.0625),
 np.float64(0.0),
 np.float64(0.0625),
 np.float64(0.125),
 np.float64(0.1875),
 np.float64(0.25),
 np.float64(0.3125),
 np.float64(0.375),
 np.float64(0.4375),
 np.float64(0.5),
 np.float64(0.5625),
 np.float64(0.625),
 np.float64(0.6875),
 np.float64(0.75),
 np.float64(0.8125),
 np.float64(0.875),
 np.float64(0.9375),
 np.float64(1.0),
 np.float64(1.0625),
 np.float64(1.125),
 np.float64(1.1875),
 np.float64(1.25),
 np.float64(1.3125),
 np.float64(1.375)]

In [13]:
test1 = {'col1': {'nested_1': 1, 'nested_2': 2}, 'col2': 2}
test2 = {'col1': 3}

test3 = [test1, test2]
x = pd.DataFrame.from_dict(test3)
x

                             col1  col2
0  {'nested_1': 1, 'nested_2': 2}   2.0
1                               3   NaN

In [16]:
for condition_name, condition_parameters in conditions.items():
    for roi in rois:
        roi_list = windowed_data.get(condition_name, {}).get(roi, [])
        sub_idx = 0
        for sub in SUBJECTS:
            electrodes_test = electrodes[roi].get(sub, [])
            if not electrodes_test:
                continue  # process_windowed_data_for_anova also skipped
            if sub_idx >= len(roi_list):
                break
            subject_data = roi_list[sub_idx]
            sub_idx += 1

            # Defensive: clamp electrode count to actual data shape.
            n_chans_data = subject_data.shape[2]
            n_chans = min(len(electrodes_test), n_chans_data)
            if n_chans_data != len(electrodes_test):
                print(f"[create_windowed_anova_dataframe] WARNING: "
                        f"{sub}/{roi}: electrode list has {len(electrodes_test)} but "
                        f"data has {n_chans_data} channels; using first {n_chans}.")

            for trial_idx in range(subject_data.shape[0]):
                for window_idx in range(subject_data.shape[1]):
                    for electrode_idx in range(n_chans):
                        electrode_name = electrodes_test[electrode_idx]
                        activity = subject_data[trial_idx, window_idx, electrode_idx]
                        data_dict = {
                            'SubjectID': sub,
                            'Electrode': electrode_name,
                            'ROI': roi,
                            'WindowCenter': window_centers[window_idx],
                            'WindowIndex': window_idx,
                            'Trial': trial_idx + 1,
                            'Activity': activity,
                        }
                        data_dict.update(condition_parameters)
                        data_for_anova.append(data_dict)

df = pd.DataFrame(data_for_anova)

In [ ]:
results_by_window = {}

# Get unique window indices
window_indices = df['WindowIndex'].unique()

test = df[df['WindowIndex'] == 0]

test2 = test[
    (test['SubjectID'] == 'D0103') &
    (test['Electrode'] == 'LFAM8') &
    (test['ROI'] == 'lpfc')
]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36])

In [71]:
test2

,SubjectID,Electrode,ROI,WindowCenter,WindowIndex,Trial,Activity,BIDS_events,congruency,congruencyProportion,switchType,switchProportion
0,D0103,LFAM8,lpfc,-0.875,0,1,-0.116866,[Stimulus/i25.0/s25.0],i,75%,s,25%
333,D0103,LFAM8,lpfc,-0.875,0,2,-1.095520,[Stimulus/i25.0/s25.0],i,75%,s,25%
666,D0103,LFAM8,lpfc,-0.875,0,3,-0.973818,[Stimulus/i25.0/s25.0],i,75%,s,25%
999,D0103,LFAM8,lpfc,-0.875,0,1,0.749343,[Stimulus/i25.0/s75.0],i,75%,s,75%
1332,D0103,LFAM8,lpfc,-0.875,0,2,-0.134652,[Stimulus/i25.0/s75.0],i,75%,s,75%
...,...,...,...,...,...,...,...,...,...,...,...,...
294039,D0103,LFAM8,lpfc,-0.875,0,5,-0.642744,[Stimulus/c75.0/r75.0],c,25%,r,75%
294372,D0103,LFAM8,lpfc,-0.875,0,6,-0.469576,[Stimulus/c75.0/r75.0],c,25%,r,75%
294705,D0103,LFAM8,lpfc,-0.875,0,7,1.015979,[Stimulus/c75.0/r75.0],c,25%,r,75%
295038,D0103,LFAM8,lpfc,-0.875,0,8,0.180228,[Stimulus/c75.0/r75.0],c,25%,r,75%
295371,D0103,LFAM8,lpfc,-0.875,0,9,0.172131,[Stimulus/c75.0/r75.0],c,25%,r,75%

In [73]:
anova_results.columns

Index(['sum_sq', 'df', 'F', 'PR(>F)'], dtype='object')

In [79]:
sig_effects

,sum_sq,df,F,PR(>F)
C(switchProportion),1.694469,1.0,4.080976,0.043674
C(congruency):C(switchType),1.906173,1.0,4.590847,0.032419
C(congruencyProportion):C(switchType),3.247922,1.0,7.822329,0.005274
C(congruency):C(switchType):C(switchProportion),1.650141,1.0,3.974217,0.046513
C(congruencyProportion):C(switchType):C(switchProportion),3.225811,1.0,7.769077,0.005430

In [76]:
test4 = [k for k in conditions[next(iter(conditions))].keys() if k != 'BIDS_events']
formula = 'Activity ~ ' + ' * '.join([f'C({k})' for k in test4])
model = ols(formula, data=test2).fit()
anova_results = anova_lm(model, typ=2)

results = []
sig_effects = anova_results[anova_results['PR(>F)'] < 0.05]

if not sig_effects.empty:
    results.append({
        'SubjectID': 'D0103',
        'Electrode': 'LFAM8',
        'ROI': 'lpfc',
        'Effects': sig_effects
    })
results

[{'SubjectID': 'D0103',
  'Electrode': 'LFAM8',
  'ROI': 'lpfc',
  'Effects':                                                       sum_sq   df         F  \
  C(switchProportion)                                 1.694469  1.0  4.080976
  C(congruency):C(switchType)                         1.906173  1.0  4.590847
  C(congruencyProportion):C(switchType)               3.247922  1.0  7.822329
  C(congruency):C(switchType):C(switchProportion)     1.650141  1.0  3.974217
  C(congruencyProportion):C(switchType):C(switchP...  3.225811  1.0  7.769077

                                                        PR(>F)
  C(switchProportion)                                 0.043674
  C(congruency):C(switchType)                         0.032419
  C(congruencyProportion):C(switchType)               0.005274
  C(congruency):C(switchType):C(switchProportion)     0.046513
  C(congruencyProportion):C(switchType):C(switchP...  0.005430  }]

In [ ]:
try:
    model = ols(formula, data=df_filtered).fit()
    anova_results = anova_lm(model, typ=2)
    
    # Store significant effects
    sig_effects = anova_results[anova_results['PR(>F)'] < 0.05]
    if not sig_effects.empty:
        results.append({
            'SubjectID': subject_id,
            'Electrode': electrode,
            'ROI': roi,
            'Effects': sig_effects
        })
except:
    continue

In [ ]:
for window_idx in window_indices:
    df_window = df[df['WindowIndex'] == window_idx]
    window_center = df_window['WindowCenter'].iloc[0]
    
    if anova_type == 'within_electrode':
        # Perform within-electrode ANOVA for this window
        results = []
        
        for subject_id in df_window['SubjectID'].unique():
            for electrode in df_window['Electrode'].unique():
                for roi in df_window['ROI'].unique():
                    df_filtered = df_window[
                        (df_window['SubjectID'] == subject_id) & 
                        (df_window['Electrode'] == electrode) & 
                        (df_window['ROI'] == roi)
                    ]
                    
                    if df_filtered.empty or len(df_filtered) < 2:
                        continue
                    
                    # Build formula
                    condition_keys = [k for k in conditions[next(iter(conditions))].keys() 
                                    if k != 'BIDS_events']
                    formula = 'Activity ~ ' + ' * '.join([f'C({k})' for k in condition_keys])
                    
                    try:
                        model = ols(formula, data=df_filtered).fit()
                        anova_results = anova_lm(model, typ=2)
                        
                        # Store significant effects
                        sig_effects = anova_results[anova_results['PR(>F)'] < 0.05]
                        if not sig_effects.empty:
                            results.append({
                                'SubjectID': subject_id,
                                'Electrode': electrode,
                                'ROI': roi,
                                'Effects': sig_effects
                            })
                    except:
                        continue
        
        results_by_window[window_center] = results
        
    elif anova_type == 'across_electrode':
        # Perform across-electrode ANOVA for this window.
        # Accumulate per-ROI results under this window so multiple ROIs
        # don't overwrite each other.
        if window_center not in results_by_window:
            results_by_window[window_center] = {}

        # Build the factor-key list once per window — exclude BIDS_events
        # because (a) it isn't an ANOVA factor and (b) its values are lists,
        # which are unhashable and would break the groupby below.
        condition_keys = [k for k in conditions[next(iter(conditions))].keys()
                            if k != 'BIDS_events']
        formula = 'Activity ~ ' + ' * '.join([f'C({k})' for k in condition_keys])

        for roi in rois:
            df_roi = df_window[df_window['ROI'] == roi]
            if df_roi.empty:
                continue

            # Average across trials for each electrode-cell
            df_averaged = df_roi.groupby(
                ['SubjectID', 'Electrode', 'ROI'] + condition_keys
            )['Activity'].mean().reset_index()

            model = ols(formula, data=df_averaged).fit()
            anova_results = anova_lm(model, typ=2)

            results_by_window[window_center][roi] = anova_results

# Save results
results_file = os.path.join(save_dir, f'{save_name}_windowed_anova_{anova_type}.json')

# Convert results to serializable format
serializable_results = {}
for window, result in results_by_window.items():
    serializable_results[str(window)] = str(result)

with open(results_file, 'w') as f:
    json.dump(serializable_results, f, indent=4)

In [ ]:
def process_windowed_data_for_anova(subjects_mne_objects, condition_names, rois, subjects, 
                                    electrodes_per_subject_roi, window_size=64, 
                                    step_size=16, sampling_rate=256):
    """
    Process data with sliding windows for ANOVA analysis.
    
    Parameters:
    -----------
    window_size : int or None
        Size of window in samples. If None, uses full epoch.
    step_size : int
        Step size for sliding window in samples.
    Slide a window over each subject's trial-level epoch data and average within
    each window to produce per-window per-channel scalars suitable for ANOVA.

    For every (condition, ROI, subject) triple that has at least one electrode in
    the ROI, this function:
      1. Picks the subject's epochs for the given condition.
      2. Restricts channels to ``electrodes_per_subject_roi[roi][subject]``.
      3. Slides a window of ``window_size`` samples with stride ``step_size`` over
         the time axis using ``general_utils.windower``.
      4. Averages within each window (collapsing the time axis inside a window)
         to produce a (n_trials, n_windows, n_channels) array.

    Subjects with **no** electrodes for the ROI are silently skipped (the output
    list for that ROI simply omits them). The downstream
    ``create_windowed_anova_dataframe`` reproduces this same skipping logic so
    list indices line up with the right subject + electrodes — see
    ``create_windowed_anova_dataframe`` for the matching invariant.

    Parameters
    ----------
    subjects_mne_objects : dict
        Nested dict ``[subject][condition_name][mne_object_type]``; we read
        ``[sub][cond]['HG_ev1_power_rescaled']``.
    condition_names : list of str
        Condition keys (e.g. ``['Stimulus_i25s25', ...]``).
    rois : list of str
        ROI names (e.g. ``['lpfc', 'occ', ...]``).
    subjects : list of str
        Subject IDs to iterate. Must be the same ordered list passed to
        ``create_windowed_anova_dataframe`` later, since that function relies on
        the same subject-skipping order.
    electrodes_per_subject_roi : dict
        ``[roi][subject] -> list of electrode names``.
    window_size : int or None, default 64
        Size of window in samples. If None, ``windower`` falls back to a single
        full-epoch window.
    step_size : int, default 16
        Stride between successive windows in samples.
    sampling_rate : int, default 256
        Currently unused (kept for API symmetry with the dataframe builder).

    Returns
    -------
    windowed_data : dict
        ``{condition_name: {roi: list_of_arrays}}`` where each list entry is a
        (n_trials, n_windows, n_channels) ndarray, one per subject that had
        electrodes for that ROI, in the same order as ``subjects``.
    """
    windowed_data = {}
    
    for condition_name in condition_names:
        windowed_data[condition_name] = {}
        
        for roi in rois:
            roi_data_list = []
            
            for sub in subjects:
                electrodes = electrodes_per_subject_roi[roi].get(sub, [])
                if not electrodes:
                    continue
                
                # Get epochs for this condition
                epochs = subjects_mne_objects[sub][condition_name]['HG_ev1_power_rescaled'].copy()
                epochs = epochs.pick_channels(electrodes)
                
                # Get data: (n_trials, n_channels, n_times)
                data = epochs.get_data()
                
                # Apply windowing to each channel and trial
                # windower expects data with time axis last by default
                windowed_trials = []
                for trial in data:
                    trial_windowed = windower(trial, window_size=window_size, 
                                             axis=-1, step_size=step_size, insert_at=0)
                    # Shape: (n_windows, n_channels, window_size)
                    windowed_trials.append(trial_windowed)
                
                windowed_trials = np.array(windowed_trials)
                # Shape: (n_trials, n_windows, n_channels, window_size)
                
                # Average within each window
                windowed_avg = np.mean(windowed_trials, axis=-1)
                # Shape: (n_trials, n_windows, n_channels)
                
                roi_data_list.append(windowed_avg)
            
            windowed_data[condition_name][roi] = roi_data_list
    
    return windowed_data

def create_windowed_anova_dataframe(windowed_data, conditions, rois, subjects,
                                    electrodes_per_subject_roi, times,
                                    window_size=None, step_size=1, sampling_rate=256):
    """
    Create DataFrame for windowed ANOVA analysis.
    Flatten the nested ``windowed_data`` structure into a long DataFrame suitable
    for per-window OLS / ANOVA fits.

    Each row is one observation: ``(subject, electrode, ROI, trial, window) ->
    Activity``, with the factor columns from ``conditions[cond]`` attached
    (e.g. ``congruency``, ``congruencyProportion``, ``switchType``,
    ``switchProportion``). ``BIDS_events`` is included verbatim; downstream
    formula-builders should drop it.

    Window centers are precomputed once (in seconds) and attached to every row
    of the corresponding window so the resulting DataFrame can be plotted /
    grouped by ``WindowCenter`` directly.

    Parameters
    ----------
    windowed_data : dict
        Output of :func:`process_windowed_data_for_anova`.
    conditions : dict
        Mapping ``{condition_name: condition_parameters}`` from
        ``experiment_conditions``. The ``condition_parameters`` dict is merged
        into every row so factor columns become available for OLS.
    rois : list of str
    electrodes_per_subject_roi : dict
        ``[roi][subject] -> list of electrode names``.
    times : array-like
        The full per-sample time vector of the epoch (used to compute window
        centers).
    window_size : int or None
        Window length in samples; when None, a single window centered at the
        epoch midpoint is produced.
    step_size : int, default 1
    sampling_rate : int, default 256

    Returns
    -------
    df : pandas.DataFrame
        Columns: ``SubjectID``, ``Electrode``, ``ROI``, ``WindowCenter``,
        ``WindowIndex``, ``Trial``, ``Activity``, plus all keys from
        ``condition_parameters`` (factor columns + ``BIDS_events``).

    Notes
    -----
    Cross-subject channel-name collisions: ``combine_single_channel_evokeds``
    renames duplicates with running suffixes (``LFMM9-0``, ``LFMM9-1``), but the
    ``Electrode`` column here stores the **un-suffixed** original name. Always
    group by ``(SubjectID, Electrode)`` together if you need a unique key.
    """
    data_for_anova = []

    # Window centers
    if window_size is not None:
        n_windows = (len(times) - window_size) // step_size + 1
        window_centers = []
        for i in range(n_windows):
            start_idx = i * step_size
            center_idx = start_idx + window_size // 2
            if center_idx < len(times):
                window_centers.append(times[center_idx])
            else:
                window_centers.append(times[-1])
    else:
        window_centers = [np.mean(times)]

    for condition_name, condition_parameters in conditions.items():
        for roi in rois:
            roi_list = windowed_data.get(condition_name, {}).get(roi, [])
            sub_idx = 0
            for sub in subjects:
                electrodes = electrodes_per_subject_roi[roi].get(sub, [])
                if not electrodes:
                    continue  # process_windowed_data_for_anova also skipped
                if sub_idx >= len(roi_list):
                    break
                subject_data = roi_list[sub_idx]
                sub_idx += 1

                # Defensive: clamp electrode count to actual data shape.
                n_chans_data = subject_data.shape[2]
                n_chans = min(len(electrodes), n_chans_data)
                if n_chans_data != len(electrodes):
                    print(f"[create_windowed_anova_dataframe] WARNING: "
                          f"{sub}/{roi}: electrode list has {len(electrodes)} but "
                          f"data has {n_chans_data} channels; using first {n_chans}.")

                for trial_idx in range(subject_data.shape[0]):
                    for window_idx in range(subject_data.shape[1]):
                        for electrode_idx in range(n_chans):
                            electrode_name = electrodes[electrode_idx]
                            activity = subject_data[trial_idx, window_idx, electrode_idx]
                            data_dict = {
                                'SubjectID': sub,
                                'Electrode': electrode_name,
                                'ROI': roi,
                                'WindowCenter': window_centers[window_idx],
                                'WindowIndex': window_idx,
                                'Trial': trial_idx + 1,
                                'Activity': activity,
                            }
                            data_dict.update(condition_parameters)
                            data_for_anova.append(data_dict)

    return pd.DataFrame(data_for_anova)

def perform_windowed_anova(df, conditions, rois, save_dir, save_name, 
                           anova_type='within_electrode'):
    """
    Fit a Type II OLS ANOVA at every time window and persist the results.

    The OLS formula is built dynamically from the keys of any single condition
    in ``conditions`` (excluding ``BIDS_events``), as
    ``Activity ~ C(f1) * C(f2) * ... * C(fn)`` — i.e. all factors plus all
    interactions. This implicitly assumes that every condition shares the same
    factor-key set; mixing condition sets with different keys here will produce
    misleading formulas.

    Two analysis modes:

    - ``'within_electrode'``: per (subject, electrode, ROI), fit OLS on the
      trial-level rows for that electrode in that window. Stores only the
      effects with uncorrected p < 0.05.
    - ``'across_electrode'``: per ROI, average activity within each
      (subject, electrode, factors) cell first, then fit OLS treating each
      electrode-cell as one observation. Stores the full ANOVA table per ROI
      per window.

    Parameters
    ----------
    df : pandas.DataFrame
        Output of :func:`create_windowed_anova_dataframe`.
    conditions : dict
        ``{condition_name: condition_parameters}``; only the first entry's keys
        are used to build the formula.
    rois : list of str
        Used only in the ``'across_electrode'`` branch.
    save_dir : str
        Directory to write the JSON output file.
    save_name : str
        Stem for the output filename
        (``{save_name}_windowed_anova_{anova_type}.json``).
    anova_type : {'within_electrode', 'across_electrode'}, default 'within_electrode'

    Returns
    -------
    results_by_window : dict
        - within_electrode: ``{window_center -> list of {SubjectID, Electrode,
          ROI, Effects (DataFrame of significant effects)}}``
        - across_electrode: ``{window_center -> {roi: anova_lm_table}}``

    Notes
    -----
    BUG (across_electrode branch): the inner loop overwrites
    ``results_by_window[window_center]`` for each ROI, so only the last ROI's
    table is preserved per window. To persist all ROIs, that branch should
    accumulate into ``{window_center: {roi: ...}}`` instead of reassigning.

    Output JSON serializes via ``str(result)``, which is lossy and only useful
    for human inspection — re-parsing the JSON back into DataFrames is not
    supported.
    """
    results_by_window = {}
    
    # Get unique window indices
    window_indices = df['WindowIndex'].unique()
    
    for window_idx in window_indices:
        df_window = df[df['WindowIndex'] == window_idx]
        window_center = df_window['WindowCenter'].iloc[0]
        
        if anova_type == 'within_electrode':
            # Perform within-electrode ANOVA for this window
            results = []
            
            for subject_id in df_window['SubjectID'].unique():
                for electrode in df_window['Electrode'].unique():
                    for roi in df_window['ROI'].unique():
                        df_filtered = df_window[
                            (df_window['SubjectID'] == subject_id) & 
                            (df_window['Electrode'] == electrode) & 
                            (df_window['ROI'] == roi)
                        ]
                        
                        if df_filtered.empty or len(df_filtered) < 2:
                            continue
                        
                        # Build formula
                        condition_keys = [k for k in conditions[next(iter(conditions))].keys() 
                                        if k != 'BIDS_events']
                        formula = 'Activity ~ ' + ' * '.join([f'C({k})' for k in condition_keys])
                        
                        try:
                            model = ols(formula, data=df_filtered).fit()
                            anova_results = anova_lm(model, typ=2)
                            
                            # Store significant effects
                            sig_effects = anova_results[anova_results['PR(>F)'] < 0.05]
                            if not sig_effects.empty:
                                results.append({
                                    'SubjectID': subject_id,
                                    'Electrode': electrode,
                                    'ROI': roi,
                                    'Effects': sig_effects
                                })
                        except:
                            continue
            
            results_by_window[window_center] = results
            
        elif anova_type == 'across_electrode':
            # Perform across-electrode ANOVA for this window.
            # Accumulate per-ROI results under this window so multiple ROIs
            # don't overwrite each other.
            if window_center not in results_by_window:
                results_by_window[window_center] = {}

            # Build the factor-key list once per window — exclude BIDS_events
            # because (a) it isn't an ANOVA factor and (b) its values are lists,
            # which are unhashable and would break the groupby below.
            condition_keys = [k for k in conditions[next(iter(conditions))].keys()
                              if k != 'BIDS_events']
            formula = 'Activity ~ ' + ' * '.join([f'C({k})' for k in condition_keys])

            for roi in rois:
                df_roi = df_window[df_window['ROI'] == roi]
                if df_roi.empty:
                    continue

                # Average across trials for each electrode-cell
                df_averaged = df_roi.groupby(
                    ['SubjectID', 'Electrode', 'ROI'] + condition_keys
                )['Activity'].mean().reset_index()

                model = ols(formula, data=df_averaged).fit()
                anova_results = anova_lm(model, typ=2)

                results_by_window[window_center][roi] = anova_results
    
    # Save results
    results_file = os.path.join(save_dir, f'{save_name}_windowed_anova_{anova_type}.json')
    
    # Convert results to serializable format
    serializable_results = {}
    for window, result in results_by_window.items():
        serializable_results[str(window)] = str(result)
    
    with open(results_file, 'w') as f:
        json.dump(serializable_results, f, indent=4)
    
    return results_by_window

In [ ]:
def main(args):





    # ------------------------------------------------------------------
    # 4. Build evokeds for all conditions
    # ------------------------------------------------------------------
    evks_dict_elecs = make_multi_channel_evokeds_for_all_conditions_and_rois(
        subjects_mne_objects, args.subjects, rois, condition_names, electrodes
    )

    # ------------------------------------------------------------------
    # 5. Statistical testing
    # ------------------------------------------------------------------
    significant_clusters = {}
    interaction_results = None

    if args.statistical_method == 'time_perm_cluster':
        print("\nRunning statistical tests comparing TWO conditions")
        if len(condition_names) != 2:
            raise ValueError("Time perm cluster stats requires exactly two conditions.")

        p_values_dict = {}
        condition1_name, condition2_name = condition_names

        for roi in rois:
            print(f"-- Processing ROI: {roi} --")
            try:
                evoked_cond1_this_roi = evks_dict_elecs[condition1_name][roi]
                evoked_cond2_this_roi = evks_dict_elecs[condition2_name][roi]

                mask_roi, p_values = time_perm_cluster_between_two_evokeds(
                    evoked_cond1_this_roi, evoked_cond2_this_roi,
                    p_thresh=args.p_thresh_for_time_perm_cluster_stats,
                    p_cluster=args.p_cluster, n_perm=args.n_perm,
                    tails=args.tails, axis=0, stat_func=args.stat_func,
                    ignore_adjacency=None,
                    permutation_type=args.permutation_type,
                    vectorized=True, n_jobs=args.n_jobs, seed=None, verbose=True,
                )

                significant_clusters[roi] = mask_roi
                p_values_dict[roi] = p_values
            except KeyError:
                print(f"   Skipping ROI {roi}: Missing prepared evoked data for "
                      f"one or both conditions.")

    elif args.statistical_method == 'anova':
        if not anova_interactions:
            raise ValueError(
                f"condition_label '{condition_label}' has no 'anova_interactions' "
                f"in the registry. Add them to enable ANOVA cluster correction."
            )
        print(f"\nRunning ANOVA-based 2-way interaction cluster correction for "
              f"{len(anova_interactions)} interaction(s) across {len(rois)} ROI(s)")
        interaction_results = run_anova_interaction_clusters(
            evks_dict_elecs, conditions, anova_interactions, rois,
            p_thresh=args.p_thresh_for_time_perm_cluster_stats,
            cluster_forming_p=args.p_cluster,
            n_perm=args.n_perm, tails=args.tails,
            seed=None, verbose=True,
        )

    # ------------------------------------------------------------------
    # 6. Plotting
    # ------------------------------------------------------------------
    plot_power_traces_for_all_rois(
        evks_dict_elecs, rois, condition_names, conditions_save_name, plot_params,
        args.window_size, args.sampling_rate,
        significant_clusters=significant_clusters or None,
        save_dir=save_dir,
        error_type='sem',
        plot_style=args.plot_style,
        save_name_suffix=elec_string_to_add_to_filename,
    )

    # If we ran the ANOVA cluster correction, draw the 16-condition mega-plot
    # with 4 stacked interaction-cluster bars + one 4-trace plot per interaction.
    if interaction_results is not None:
        plot_anova_interaction_results(
            evks_dict_elecs, conditions, condition_names, conditions_save_name,
            rois, anova_interactions, interaction_results,
            plot_style=args.plot_style, save_dir=save_dir,
            save_name_suffix=elec_string_to_add_to_filename, error_type='sem',
        )

    # ------------------------------------------------------------------
    # 7. Subtraction-pair plotting (driven by registry)
    # ------------------------------------------------------------------
    if subtraction_pairs:
        # All names needed must be present in evks_dict_elecs
        usable_pairs = [p for p in subtraction_pairs
                        if p[0] in evks_dict_elecs and p[1] in evks_dict_elecs]
        if usable_pairs:
            subtracted_evks_dict_elecs = create_subtracted_evokeds_dict(
                evks_dict_elecs, usable_pairs, rois
            )
            sub_pair_names = ['-'.join(pair) for pair in usable_pairs]
            sub_save_name = (f"{condition_label}_subtractions_"
                             f"{args.epochs_root_file}_"
                             f"{len(args.subjects)}_subjects")
            plot_power_traces_for_all_rois(
                subtracted_evks_dict_elecs, rois, sub_pair_names, sub_save_name,
                plot_params, save_dir=save_dir,
                window_size=args.window_size, sampling_rate=args.sampling_rate,
                error_type='sem',
                plot_style=args.plot_style,
                save_name_suffix=elec_string_to_add_to_filename,
            )
        else:
            print("[subtraction] No usable subtraction pairs (condition keys "
                  "missing from evks_dict).")

    # ------------------------------------------------------------------
    # 8. Save results
    # ------------------------------------------------------------------
    results_save_dir = os.path.join(save_dir, 'saved_results')
    os.makedirs(results_save_dir, exist_ok=True)

    for condition_name in condition_names:
        for roi in rois:
            evk = evks_dict_elecs[condition_name][roi]
            if evk is not None:
                np.savez(
                    os.path.join(
                        results_save_dir,
                        f'{conditions_save_name}_{condition_name}_{roi}_evoked.npz'
                    ),
                    data=evk.data, times=evk.times, ch_names=evk.ch_names
                )

    if significant_clusters:
        np.savez(
            os.path.join(results_save_dir,
                         f'{conditions_save_name}_significant_clusters.npz'),
            **significant_clusters
        )

    if interaction_results is not None:
        # Persist as one file per ROI / interaction (masks + p values)
        for roi, by_inter in interaction_results.items():
            for inter_name, info in by_inter.items():
                np.savez(
                    os.path.join(
                        results_save_dir,
                        f'{conditions_save_name}_{roi}_{inter_name}_interaction_cluster.npz'
                    ),
                    mask=info['mask'],
                    t_obs=info['t_obs'],
                    cluster_p_values=info['cluster_p_values'],
                )

    metadata = {
        'condition_label': condition_label,
        'condition_names': condition_names,
        'rois': rois,
        'conditions_save_name': conditions_save_name,
        'sfreq': args.sampling_rate,
        'statistical_method': args.statistical_method,
        'anova_factors': anova_factors,
        'anova_interactions': [
            {'name': i['name'], 'factors': i['factors'],
             'label': i.get('label', i['name'])}
            for i in anova_interactions
        ] if anova_interactions else [],
    }
    with open(os.path.join(results_save_dir,
                           f'{conditions_save_name}_metadata.json'), 'w') as f:
        json.dump(metadata, f, indent=2)


if __name__ == "__main__":
    if len(sys.argv) == 1:
        pass
    else:
        print("This script should be called via run_power_traces_dcc.py")
        print("Direct command-line execution is not supported with complex parameters.")
        sys.exit(1)

In [3]:
import numpy as np, os
from src.analysis.utils.general_utils import load_mne_objects

erf="Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_3.0s_filterbank_hilbert_stat_func_ttest_ind_equal_var_False_nan_policy_omit"

ep = load_mne_objects('D0121', erf, 'GlobalLocal',
                      just_HG_ev1_rescaled=True)['HG_ev1_power_rescaled']["Accuracy1.0"]

picks = ['LFMI9', 'LFMI8', 'LFA2', 'LFO14', 'LFO15', 'LFMI5', 'LFAS9']
x = ep.get_data(picks=picks)                 # (trials, ch, times)
pre = ep.times <= 0
worst = np.nanmax(np.abs(x[:, :, pre]), axis=2)      # (trials, ch)

bad = {367, 334}
for j, ch in enumerate(picks):
    order = np.argsort(worst[:, j])[::-1][:3]
    print(f"{ch:8s} top-3 trials {list(order)}  vals {np.round(worst[order, j], 1)}"
          f"  {'<- same two' if set(order[:2]) == bad else ''}")

Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0121/D0121_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_3.0s_filterbank_hilbert_stat_func_ttest_ind_equal_var_False_nan_policy_omit_HG_ev1_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
Reading /cwork/jz421/BIDS-1.1_GlobalLocal/BIDS/derivatives/freqFilt/figs/D0121/D0121_Stimulus_-1.0to1.5sec_0.5sec_within-1.0-0.0sec_base_decFactor_8_outliers_10_drop_and_nan_thresh_perc_5.0_70.0-150.0_Hz_padLength_3.0s_filterbank_hilbert_stat_func_ttest_ind_equal_var_False_nan_policy_omit_HG_ev1_power_rescaled-epo.fif ...
    Found the data of interest:
        t =   -1000.00 ...    1500.00 ms
        0 CTF compensation matrices available
Adding metadata with 29 columns
448 matching events found
No baseline correction applied
0 projection items activated
Replacing existing metadata with 29 columns
LFMI9    top-3 trials [np.int64(27), np.int64(367), np.int64(333)]  vals [nan nan nan]
LFMI8    top-3 trials [np.int64(260), np.int64(35), np.int64(34)]  vals [nan nan nan]
LFA2     top-3 trials [np.int64(35), np.int64(36), np.int64(345)]  vals [nan nan nan]
LFO14    top-3 trials [np.int64(345), np.int64(305), np.int64(225)]  vals [277.7  43.3  13.1]
LFO15    top-3 trials [np.int64(345), np.int64(305), np.int64(199)]  vals [199.6  58.1  15.2]
LFMI5    top-3 trials [np.int64(333), np.int64(285), np.int64(16)]  vals [nan nan nan]
LFAS9    top-3 trials [np.int64(343), np.int64(345), np.int64(369)]  vals [  nan 137.4  14.2]

/tmp/ipykernel_3063525/369323578.py:12: RuntimeWarning: All-NaN slice encountered
  worst = np.nanmax(np.abs(x[:, :, pre]), axis=2)      # (trials, ch)

In [5]:
x = ep.get_data(picks=['LFMI5'])[:, 0, :]
pre = ep.times <= 0
worst = np.nanmax(np.abs(np.where(np.isnan(x), 0, x))[:, pre], axis=1)
n_nan = np.isnan(x[:, 0]).sum()
print(f"NaN at t=-1: {n_nan}/{len(x)} trials")
for i in np.argsort(worst)[::-1][:8]:
    print(f"trial {i:4d}  max|z| pre {worst[i]:10.2f}")

NaN at t=-1: 13/400 trials
trial  367  max|z| pre     331.40
trial   43  max|z| pre      21.60
trial  146  max|z| pre      16.14
trial  281  max|z| pre      13.81
trial   18  max|z| pre      13.13
trial   22  max|z| pre      11.90
trial   21  max|z| pre      10.78
trial  254  max|z| pre      10.31